/*
Zippendo Public API

Public API documentation for Zippendo. Authenticate using your API token (Bearer token prefixed with zipp_).

API version: 1.0.0
Contact: support@zippendo.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package zippendo

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ListOrgWebhookDeliveries200ResponseDataInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ListOrgWebhookDeliveries200ResponseDataInner{}

// ListOrgWebhookDeliveries200ResponseDataInner struct for ListOrgWebhookDeliveries200ResponseDataInner
type ListOrgWebhookDeliveries200ResponseDataInner struct {
	// Delivery log ID
	Id string `json:"id"`
	// ID of the webhook this delivery belongs to
	WebhookId string `json:"webhookId"`
	// Event type that was delivered
	Event string `json:"event"`
	// JSON payload that was sent
	Payload interface{} `json:"payload"`
	// HTTP status code returned by the endpoint
	StatusCode NullableFloat32 `json:"statusCode"`
	// Response body returned by the endpoint
	Response NullableString `json:"response"`
	// Request duration in milliseconds
	Duration NullableFloat32 `json:"duration"`
	// Whether the delivery succeeded
	Success bool `json:"success"`
	// Delivery attempt number
	Attempt float32 `json:"attempt"`
	// Error message if the delivery failed
	Error NullableString `json:"error"`
	// Delivery timestamp (ISO 8601)
	CreatedAt string `json:"createdAt"`
}

type _ListOrgWebhookDeliveries200ResponseDataInner ListOrgWebhookDeliveries200ResponseDataInner

// NewListOrgWebhookDeliveries200ResponseDataInner instantiates a new ListOrgWebhookDeliveries200ResponseDataInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewListOrgWebhookDeliveries200ResponseDataInner(id string, webhookId string, event string, payload interface{}, statusCode NullableFloat32, response NullableString, duration NullableFloat32, success bool, attempt float32, error_ NullableString, createdAt string) *ListOrgWebhookDeliveries200ResponseDataInner {
	this := ListOrgWebhookDeliveries200ResponseDataInner{}
	this.Id = id
	this.WebhookId = webhookId
	this.Event = event
	this.Payload = payload
	this.StatusCode = statusCode
	this.Response = response
	this.Duration = duration
	this.Success = success
	this.Attempt = attempt
	this.Error = error_
	this.CreatedAt = createdAt
	return &this
}

// NewListOrgWebhookDeliveries200ResponseDataInnerWithDefaults instantiates a new ListOrgWebhookDeliveries200ResponseDataInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewListOrgWebhookDeliveries200ResponseDataInnerWithDefaults() *ListOrgWebhookDeliveries200ResponseDataInner {
	this := ListOrgWebhookDeliveries200ResponseDataInner{}
	return &this
}

// GetId returns the Id field value
func (o *ListOrgWebhookDeliveries200ResponseDataInner) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *ListOrgWebhookDeliveries200ResponseDataInner) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *ListOrgWebhookDeliveries200ResponseDataInner) SetId(v string) {
	o.Id = v
}

// GetWebhookId returns the WebhookId field value
func (o *ListOrgWebhookDeliveries200ResponseDataInner) GetWebhookId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.WebhookId
}

// GetWebhookIdOk returns a tuple with the WebhookId field value
// and a boolean to check if the value has been set.
func (o *ListOrgWebhookDeliveries200ResponseDataInner) GetWebhookIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.WebhookId, true
}

// SetWebhookId sets field value
func (o *ListOrgWebhookDeliveries200ResponseDataInner) SetWebhookId(v string) {
	o.WebhookId = v
}

// GetEvent returns the Event field value
func (o *ListOrgWebhookDeliveries200ResponseDataInner) GetEvent() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Event
}

// GetEventOk returns a tuple with the Event field value
// and a boolean to check if the value has been set.
func (o *ListOrgWebhookDeliveries200ResponseDataInner) GetEventOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Event, true
}

// SetEvent sets field value
func (o *ListOrgWebhookDeliveries200ResponseDataInner) SetEvent(v string) {
	o.Event = v
}

// GetPayload returns the Payload field value
// If the value is explicit nil, the zero value for interface{} will be returned
func (o *ListOrgWebhookDeliveries200ResponseDataInner) GetPayload() interface{} {
	if o == nil {
		var ret interface{}
		return ret
	}

	return o.Payload
}

// GetPayloadOk returns a tuple with the Payload field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ListOrgWebhookDeliveries200ResponseDataInner) GetPayloadOk() (*interface{}, bool) {
	if o == nil || IsNil(o.Payload) {
		return nil, false
	}
	return &o.Payload, true
}

// SetPayload sets field value
func (o *ListOrgWebhookDeliveries200ResponseDataInner) SetPayload(v interface{}) {
	o.Payload = v
}

// GetStatusCode returns the StatusCode field value
// If the value is explicit nil, the zero value for float32 will be returned
func (o *ListOrgWebhookDeliveries200ResponseDataInner) GetStatusCode() float32 {
	if o == nil || o.StatusCode.Get() == nil {
		var ret float32
		return ret
	}

	return *o.StatusCode.Get()
}

// GetStatusCodeOk returns a tuple with the StatusCode field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ListOrgWebhookDeliveries200ResponseDataInner) GetStatusCodeOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return o.StatusCode.Get(), o.StatusCode.IsSet()
}

// SetStatusCode sets field value
func (o *ListOrgWebhookDeliveries200ResponseDataInner) SetStatusCode(v float32) {
	o.StatusCode.Set(&v)
}

// GetResponse returns the Response field value
// If the value is explicit nil, the zero value for string will be returned
func (o *ListOrgWebhookDeliveries200ResponseDataInner) GetResponse() string {
	if o == nil || o.Response.Get() == nil {
		var ret string
		return ret
	}

	return *o.Response.Get()
}

// GetResponseOk returns a tuple with the Response field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ListOrgWebhookDeliveries200ResponseDataInner) GetResponseOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Response.Get(), o.Response.IsSet()
}

// SetResponse sets field value
func (o *ListOrgWebhookDeliveries200ResponseDataInner) SetResponse(v string) {
	o.Response.Set(&v)
}

// GetDuration returns the Duration field value
// If the value is explicit nil, the zero value for float32 will be returned
func (o *ListOrgWebhookDeliveries200ResponseDataInner) GetDuration() float32 {
	if o == nil || o.Duration.Get() == nil {
		var ret float32
		return ret
	}

	return *o.Duration.Get()
}

// GetDurationOk returns a tuple with the Duration field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ListOrgWebhookDeliveries200ResponseDataInner) GetDurationOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return o.Duration.Get(), o.Duration.IsSet()
}

// SetDuration sets field value
func (o *ListOrgWebhookDeliveries200ResponseDataInner) SetDuration(v float32) {
	o.Duration.Set(&v)
}

// GetSuccess returns the Success field value
func (o *ListOrgWebhookDeliveries200ResponseDataInner) GetSuccess() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.Success
}

// GetSuccessOk returns a tuple with the Success field value
// and a boolean to check if the value has been set.
func (o *ListOrgWebhookDeliveries200ResponseDataInner) GetSuccessOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Success, true
}

// SetSuccess sets field value
func (o *ListOrgWebhookDeliveries200ResponseDataInner) SetSuccess(v bool) {
	o.Success = v
}

// GetAttempt returns the Attempt field value
func (o *ListOrgWebhookDeliveries200ResponseDataInner) GetAttempt() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.Attempt
}

// GetAttemptOk returns a tuple with the Attempt field value
// and a boolean to check if the value has been set.
func (o *ListOrgWebhookDeliveries200ResponseDataInner) GetAttemptOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Attempt, true
}

// SetAttempt sets field value
func (o *ListOrgWebhookDeliveries200ResponseDataInner) SetAttempt(v float32) {
	o.Attempt = v
}

// GetError returns the Error field value
// If the value is explicit nil, the zero value for string will be returned
func (o *ListOrgWebhookDeliveries200ResponseDataInner) GetError() string {
	if o == nil || o.Error.Get() == nil {
		var ret string
		return ret
	}

	return *o.Error.Get()
}

// GetErrorOk returns a tuple with the Error field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ListOrgWebhookDeliveries200ResponseDataInner) GetErrorOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Error.Get(), o.Error.IsSet()
}

// SetError sets field value
func (o *ListOrgWebhookDeliveries200ResponseDataInner) SetError(v string) {
	o.Error.Set(&v)
}

// GetCreatedAt returns the CreatedAt field value
func (o *ListOrgWebhookDeliveries200ResponseDataInner) GetCreatedAt() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value
// and a boolean to check if the value has been set.
func (o *ListOrgWebhookDeliveries200ResponseDataInner) GetCreatedAtOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CreatedAt, true
}

// SetCreatedAt sets field value
func (o *ListOrgWebhookDeliveries200ResponseDataInner) SetCreatedAt(v string) {
	o.CreatedAt = v
}

func (o ListOrgWebhookDeliveries200ResponseDataInner) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ListOrgWebhookDeliveries200ResponseDataInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["webhookId"] = o.WebhookId
	toSerialize["event"] = o.Event
	if o.Payload != nil {
		toSerialize["payload"] = o.Payload
	}
	toSerialize["statusCode"] = o.StatusCode.Get()
	toSerialize["response"] = o.Response.Get()
	toSerialize["duration"] = o.Duration.Get()
	toSerialize["success"] = o.Success
	toSerialize["attempt"] = o.Attempt
	toSerialize["error"] = o.Error.Get()
	toSerialize["createdAt"] = o.CreatedAt
	return toSerialize, nil
}

func (o *ListOrgWebhookDeliveries200ResponseDataInner) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"webhookId",
		"event",
		"payload",
		"statusCode",
		"response",
		"duration",
		"success",
		"attempt",
		"error",
		"createdAt",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varListOrgWebhookDeliveries200ResponseDataInner := _ListOrgWebhookDeliveries200ResponseDataInner{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varListOrgWebhookDeliveries200ResponseDataInner)

	if err != nil {
		return err
	}

	*o = ListOrgWebhookDeliveries200ResponseDataInner(varListOrgWebhookDeliveries200ResponseDataInner)

	return err
}

type NullableListOrgWebhookDeliveries200ResponseDataInner struct {
	value *ListOrgWebhookDeliveries200ResponseDataInner
	isSet bool
}

func (v NullableListOrgWebhookDeliveries200ResponseDataInner) Get() *ListOrgWebhookDeliveries200ResponseDataInner {
	return v.value
}

func (v *NullableListOrgWebhookDeliveries200ResponseDataInner) Set(val *ListOrgWebhookDeliveries200ResponseDataInner) {
	v.value = val
	v.isSet = true
}

func (v NullableListOrgWebhookDeliveries200ResponseDataInner) IsSet() bool {
	return v.isSet
}

func (v *NullableListOrgWebhookDeliveries200ResponseDataInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableListOrgWebhookDeliveries200ResponseDataInner(val *ListOrgWebhookDeliveries200ResponseDataInner) *NullableListOrgWebhookDeliveries200ResponseDataInner {
	return &NullableListOrgWebhookDeliveries200ResponseDataInner{value: val, isSet: true}
}

func (v NullableListOrgWebhookDeliveries200ResponseDataInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableListOrgWebhookDeliveries200ResponseDataInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


