/*
Zippendo Public API

Public API documentation for Zippendo. Authenticate using your API token (Bearer token prefixed with zipp_).  **Brands (sub-accounts).** An organization can be split into brands, each keeping its own orders, shipments and configuration separate. There are two ways to scope requests to one brand, and NEITHER changes any request body:  1. **Bind the token.** Create an API token with a `brandId` and every request it makes is confined    to that brand — reads filtered, writes stamped. This is the recommended way to give a single    brand's team its own credential. 2. **Send the `X-Zippendo-Brand` header.** An organization-wide token can scope an individual    request by sending the brand's id or slug in this header. Most SDKs let you set it once on the    client so every call inherits it.  A brand-bound token that receives an `X-Zippendo-Brand` header naming a different brand is rejected with `403 BRAND_ACCESS_DENIED` — the binding is never widened. Omit both and requests cover the whole organization, which is the behaviour of every existing token.  Records that belong to no brand carry `brandId: null`. Configuration (carriers, shipping rules, addresses) with a null brand is organization-wide and remains visible inside every brand; orders and shipments with a null brand are only visible organization-wide.

API version: 1.0.0
Contact: support@zippendo.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package zippendo

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ListApiTokens200ResponseDataInnerCreatedBy type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ListApiTokens200ResponseDataInnerCreatedBy{}

// ListApiTokens200ResponseDataInnerCreatedBy struct for ListApiTokens200ResponseDataInnerCreatedBy
type ListApiTokens200ResponseDataInnerCreatedBy struct {
	// Creator user identifier
	Id string `json:"id"`
	// Creator full name
	Name NullableString `json:"name"`
	// Creator email address
	Email string `json:"email"`
}

type _ListApiTokens200ResponseDataInnerCreatedBy ListApiTokens200ResponseDataInnerCreatedBy

// NewListApiTokens200ResponseDataInnerCreatedBy instantiates a new ListApiTokens200ResponseDataInnerCreatedBy object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewListApiTokens200ResponseDataInnerCreatedBy(id string, name NullableString, email string) *ListApiTokens200ResponseDataInnerCreatedBy {
	this := ListApiTokens200ResponseDataInnerCreatedBy{}
	this.Id = id
	this.Name = name
	this.Email = email
	return &this
}

// NewListApiTokens200ResponseDataInnerCreatedByWithDefaults instantiates a new ListApiTokens200ResponseDataInnerCreatedBy object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewListApiTokens200ResponseDataInnerCreatedByWithDefaults() *ListApiTokens200ResponseDataInnerCreatedBy {
	this := ListApiTokens200ResponseDataInnerCreatedBy{}
	return &this
}

// GetId returns the Id field value
func (o *ListApiTokens200ResponseDataInnerCreatedBy) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *ListApiTokens200ResponseDataInnerCreatedBy) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *ListApiTokens200ResponseDataInnerCreatedBy) SetId(v string) {
	o.Id = v
}

// GetName returns the Name field value
// If the value is explicit nil, the zero value for string will be returned
func (o *ListApiTokens200ResponseDataInnerCreatedBy) GetName() string {
	if o == nil || o.Name.Get() == nil {
		var ret string
		return ret
	}

	return *o.Name.Get()
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ListApiTokens200ResponseDataInnerCreatedBy) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Name.Get(), o.Name.IsSet()
}

// SetName sets field value
func (o *ListApiTokens200ResponseDataInnerCreatedBy) SetName(v string) {
	o.Name.Set(&v)
}

// GetEmail returns the Email field value
func (o *ListApiTokens200ResponseDataInnerCreatedBy) GetEmail() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Email
}

// GetEmailOk returns a tuple with the Email field value
// and a boolean to check if the value has been set.
func (o *ListApiTokens200ResponseDataInnerCreatedBy) GetEmailOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Email, true
}

// SetEmail sets field value
func (o *ListApiTokens200ResponseDataInnerCreatedBy) SetEmail(v string) {
	o.Email = v
}

func (o ListApiTokens200ResponseDataInnerCreatedBy) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ListApiTokens200ResponseDataInnerCreatedBy) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["name"] = o.Name.Get()
	toSerialize["email"] = o.Email
	return toSerialize, nil
}

func (o *ListApiTokens200ResponseDataInnerCreatedBy) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"name",
		"email",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varListApiTokens200ResponseDataInnerCreatedBy := _ListApiTokens200ResponseDataInnerCreatedBy{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varListApiTokens200ResponseDataInnerCreatedBy)

	if err != nil {
		return err
	}

	*o = ListApiTokens200ResponseDataInnerCreatedBy(varListApiTokens200ResponseDataInnerCreatedBy)

	return err
}

type NullableListApiTokens200ResponseDataInnerCreatedBy struct {
	value *ListApiTokens200ResponseDataInnerCreatedBy
	isSet bool
}

func (v NullableListApiTokens200ResponseDataInnerCreatedBy) Get() *ListApiTokens200ResponseDataInnerCreatedBy {
	return v.value
}

func (v *NullableListApiTokens200ResponseDataInnerCreatedBy) Set(val *ListApiTokens200ResponseDataInnerCreatedBy) {
	v.value = val
	v.isSet = true
}

func (v NullableListApiTokens200ResponseDataInnerCreatedBy) IsSet() bool {
	return v.isSet
}

func (v *NullableListApiTokens200ResponseDataInnerCreatedBy) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableListApiTokens200ResponseDataInnerCreatedBy(val *ListApiTokens200ResponseDataInnerCreatedBy) *NullableListApiTokens200ResponseDataInnerCreatedBy {
	return &NullableListApiTokens200ResponseDataInnerCreatedBy{value: val, isSet: true}
}

func (v NullableListApiTokens200ResponseDataInnerCreatedBy) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableListApiTokens200ResponseDataInnerCreatedBy) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


