/*
Zippendo Public API

Public API documentation for Zippendo. Authenticate using your API token (Bearer token prefixed with zipp_).

API version: 1.0.0
Contact: support@zippendo.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package zippendo

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the BatchSendShipmentsRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &BatchSendShipmentsRequest{}

// BatchSendShipmentsRequest struct for BatchSendShipmentsRequest
type BatchSendShipmentsRequest struct {
	// IDs of the shipments to book. Each must be in `pending` or `error` status; duplicates are ignored. Max 100 per request.
	ShipmentIds []string `json:"shipmentIds"`
}

type _BatchSendShipmentsRequest BatchSendShipmentsRequest

// NewBatchSendShipmentsRequest instantiates a new BatchSendShipmentsRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewBatchSendShipmentsRequest(shipmentIds []string) *BatchSendShipmentsRequest {
	this := BatchSendShipmentsRequest{}
	this.ShipmentIds = shipmentIds
	return &this
}

// NewBatchSendShipmentsRequestWithDefaults instantiates a new BatchSendShipmentsRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewBatchSendShipmentsRequestWithDefaults() *BatchSendShipmentsRequest {
	this := BatchSendShipmentsRequest{}
	return &this
}

// GetShipmentIds returns the ShipmentIds field value
func (o *BatchSendShipmentsRequest) GetShipmentIds() []string {
	if o == nil {
		var ret []string
		return ret
	}

	return o.ShipmentIds
}

// GetShipmentIdsOk returns a tuple with the ShipmentIds field value
// and a boolean to check if the value has been set.
func (o *BatchSendShipmentsRequest) GetShipmentIdsOk() ([]string, bool) {
	if o == nil {
		return nil, false
	}
	return o.ShipmentIds, true
}

// SetShipmentIds sets field value
func (o *BatchSendShipmentsRequest) SetShipmentIds(v []string) {
	o.ShipmentIds = v
}

func (o BatchSendShipmentsRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o BatchSendShipmentsRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["shipmentIds"] = o.ShipmentIds
	return toSerialize, nil
}

func (o *BatchSendShipmentsRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"shipmentIds",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varBatchSendShipmentsRequest := _BatchSendShipmentsRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varBatchSendShipmentsRequest)

	if err != nil {
		return err
	}

	*o = BatchSendShipmentsRequest(varBatchSendShipmentsRequest)

	return err
}

type NullableBatchSendShipmentsRequest struct {
	value *BatchSendShipmentsRequest
	isSet bool
}

func (v NullableBatchSendShipmentsRequest) Get() *BatchSendShipmentsRequest {
	return v.value
}

func (v *NullableBatchSendShipmentsRequest) Set(val *BatchSendShipmentsRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableBatchSendShipmentsRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableBatchSendShipmentsRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableBatchSendShipmentsRequest(val *BatchSendShipmentsRequest) *NullableBatchSendShipmentsRequest {
	return &NullableBatchSendShipmentsRequest{value: val, isSet: true}
}

func (v NullableBatchSendShipmentsRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableBatchSendShipmentsRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


