/*
Zippendo Public API

Public API documentation for Zippendo. Authenticate using your API token (Bearer token prefixed with zipp_).

API version: 1.0.0
Contact: support@zippendo.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package zippendo

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the CreateShipmentRequestPickupDetails type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateShipmentRequestPickupDetails{}

// CreateShipmentRequestPickupDetails struct for CreateShipmentRequestPickupDetails
type CreateShipmentRequestPickupDetails struct {
	// Requested pickup date (YYYY-MM-DD).
	Date string `json:"date"`
	// Requested earliest pickup time (HH:MM:SS).
	From string `json:"from"`
	// Requested latest pickup time (HH:MM:SS).
	To string `json:"to"`
	// Pickup instruction to the carrier.
	Instruction *string `json:"instruction,omitempty"`
}

type _CreateShipmentRequestPickupDetails CreateShipmentRequestPickupDetails

// NewCreateShipmentRequestPickupDetails instantiates a new CreateShipmentRequestPickupDetails object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateShipmentRequestPickupDetails(date string, from string, to string) *CreateShipmentRequestPickupDetails {
	this := CreateShipmentRequestPickupDetails{}
	this.Date = date
	this.From = from
	this.To = to
	return &this
}

// NewCreateShipmentRequestPickupDetailsWithDefaults instantiates a new CreateShipmentRequestPickupDetails object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateShipmentRequestPickupDetailsWithDefaults() *CreateShipmentRequestPickupDetails {
	this := CreateShipmentRequestPickupDetails{}
	return &this
}

// GetDate returns the Date field value
func (o *CreateShipmentRequestPickupDetails) GetDate() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Date
}

// GetDateOk returns a tuple with the Date field value
// and a boolean to check if the value has been set.
func (o *CreateShipmentRequestPickupDetails) GetDateOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Date, true
}

// SetDate sets field value
func (o *CreateShipmentRequestPickupDetails) SetDate(v string) {
	o.Date = v
}

// GetFrom returns the From field value
func (o *CreateShipmentRequestPickupDetails) GetFrom() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.From
}

// GetFromOk returns a tuple with the From field value
// and a boolean to check if the value has been set.
func (o *CreateShipmentRequestPickupDetails) GetFromOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.From, true
}

// SetFrom sets field value
func (o *CreateShipmentRequestPickupDetails) SetFrom(v string) {
	o.From = v
}

// GetTo returns the To field value
func (o *CreateShipmentRequestPickupDetails) GetTo() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.To
}

// GetToOk returns a tuple with the To field value
// and a boolean to check if the value has been set.
func (o *CreateShipmentRequestPickupDetails) GetToOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.To, true
}

// SetTo sets field value
func (o *CreateShipmentRequestPickupDetails) SetTo(v string) {
	o.To = v
}

// GetInstruction returns the Instruction field value if set, zero value otherwise.
func (o *CreateShipmentRequestPickupDetails) GetInstruction() string {
	if o == nil || IsNil(o.Instruction) {
		var ret string
		return ret
	}
	return *o.Instruction
}

// GetInstructionOk returns a tuple with the Instruction field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateShipmentRequestPickupDetails) GetInstructionOk() (*string, bool) {
	if o == nil || IsNil(o.Instruction) {
		return nil, false
	}
	return o.Instruction, true
}

// HasInstruction returns a boolean if a field has been set.
func (o *CreateShipmentRequestPickupDetails) HasInstruction() bool {
	if o != nil && !IsNil(o.Instruction) {
		return true
	}

	return false
}

// SetInstruction gets a reference to the given string and assigns it to the Instruction field.
func (o *CreateShipmentRequestPickupDetails) SetInstruction(v string) {
	o.Instruction = &v
}

func (o CreateShipmentRequestPickupDetails) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateShipmentRequestPickupDetails) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["date"] = o.Date
	toSerialize["from"] = o.From
	toSerialize["to"] = o.To
	if !IsNil(o.Instruction) {
		toSerialize["instruction"] = o.Instruction
	}
	return toSerialize, nil
}

func (o *CreateShipmentRequestPickupDetails) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"date",
		"from",
		"to",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCreateShipmentRequestPickupDetails := _CreateShipmentRequestPickupDetails{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varCreateShipmentRequestPickupDetails)

	if err != nil {
		return err
	}

	*o = CreateShipmentRequestPickupDetails(varCreateShipmentRequestPickupDetails)

	return err
}

type NullableCreateShipmentRequestPickupDetails struct {
	value *CreateShipmentRequestPickupDetails
	isSet bool
}

func (v NullableCreateShipmentRequestPickupDetails) Get() *CreateShipmentRequestPickupDetails {
	return v.value
}

func (v *NullableCreateShipmentRequestPickupDetails) Set(val *CreateShipmentRequestPickupDetails) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateShipmentRequestPickupDetails) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateShipmentRequestPickupDetails) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateShipmentRequestPickupDetails(val *CreateShipmentRequestPickupDetails) *NullableCreateShipmentRequestPickupDetails {
	return &NullableCreateShipmentRequestPickupDetails{value: val, isSet: true}
}

func (v NullableCreateShipmentRequestPickupDetails) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateShipmentRequestPickupDetails) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


