/*
Zippendo Public API

Public API documentation for Zippendo. Authenticate using your API token (Bearer token prefixed with zipp_).  **Brands (sub-accounts).** An organization can be split into brands, each keeping its own orders, shipments and configuration separate. There are two ways to scope requests to one brand, and NEITHER changes any request body:  1. **Bind the token.** Create an API token with a `brandId` and every request it makes is confined    to that brand — reads filtered, writes stamped. This is the recommended way to give a single    brand's team its own credential. 2. **Send the `X-Zippendo-Brand` header.** An organization-wide token can scope an individual    request by sending the brand's id or slug in this header. Most SDKs let you set it once on the    client so every call inherits it.  A brand-bound token that receives an `X-Zippendo-Brand` header naming a different brand is rejected with `403 BRAND_ACCESS_DENIED` — the binding is never widened. Omit both and requests cover the whole organization, which is the behaviour of every existing token.  Records that belong to no brand carry `brandId: null`. Configuration (carriers, shipping rules, addresses) with a null brand is organization-wide and remains visible inside every brand; orders and shipments with a null brand are only visible organization-wide.

API version: 1.0.0
Contact: support@zippendo.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package zippendo

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ListOrders200ResponseDataInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ListOrders200ResponseDataInner{}

// ListOrders200ResponseDataInner struct for ListOrders200ResponseDataInner
type ListOrders200ResponseDataInner struct {
	// Unique order ID.
	Id string `json:"id"`
	// Human-readable order number.
	OrderNumber string `json:"orderNumber"`
	// Customer full name.
	CustomerName NullableString `json:"customerName,omitempty"`
	// Customer email address.
	CustomerEmail NullableString `json:"customerEmail,omitempty"`
	// Order fulfilment status derived from its shipments.
	Status string `json:"status"`
	// Brand this record belongs to, or null when it is organization-wide
	BrandId NullableString `json:"brandId"`
	// Order subtotal before shipping and tax.
	SubtotalAmount NullableFloat32 `json:"subtotalAmount,omitempty"`
	// Order grand total.
	TotalAmount NullableFloat32 `json:"totalAmount,omitempty"`
	// ISO 4217 currency code.
	Currency NullableString `json:"currency,omitempty"`
	// Number of shipments created for the order.
	ShipmentCount int32 `json:"shipmentCount"`
	OrderChannel ListOrders200ResponseDataInnerOrderChannel `json:"orderChannel"`
	// Creation timestamp (ISO 8601).
	CreatedAt string `json:"createdAt"`
	// Last update timestamp (ISO 8601).
	UpdatedAt string `json:"updatedAt"`
}

type _ListOrders200ResponseDataInner ListOrders200ResponseDataInner

// NewListOrders200ResponseDataInner instantiates a new ListOrders200ResponseDataInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewListOrders200ResponseDataInner(id string, orderNumber string, status string, brandId NullableString, shipmentCount int32, orderChannel ListOrders200ResponseDataInnerOrderChannel, createdAt string, updatedAt string) *ListOrders200ResponseDataInner {
	this := ListOrders200ResponseDataInner{}
	this.Id = id
	this.OrderNumber = orderNumber
	this.Status = status
	this.BrandId = brandId
	this.ShipmentCount = shipmentCount
	this.OrderChannel = orderChannel
	this.CreatedAt = createdAt
	this.UpdatedAt = updatedAt
	return &this
}

// NewListOrders200ResponseDataInnerWithDefaults instantiates a new ListOrders200ResponseDataInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewListOrders200ResponseDataInnerWithDefaults() *ListOrders200ResponseDataInner {
	this := ListOrders200ResponseDataInner{}
	return &this
}

// GetId returns the Id field value
func (o *ListOrders200ResponseDataInner) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *ListOrders200ResponseDataInner) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *ListOrders200ResponseDataInner) SetId(v string) {
	o.Id = v
}

// GetOrderNumber returns the OrderNumber field value
func (o *ListOrders200ResponseDataInner) GetOrderNumber() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.OrderNumber
}

// GetOrderNumberOk returns a tuple with the OrderNumber field value
// and a boolean to check if the value has been set.
func (o *ListOrders200ResponseDataInner) GetOrderNumberOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.OrderNumber, true
}

// SetOrderNumber sets field value
func (o *ListOrders200ResponseDataInner) SetOrderNumber(v string) {
	o.OrderNumber = v
}

// GetCustomerName returns the CustomerName field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ListOrders200ResponseDataInner) GetCustomerName() string {
	if o == nil || IsNil(o.CustomerName.Get()) {
		var ret string
		return ret
	}
	return *o.CustomerName.Get()
}

// GetCustomerNameOk returns a tuple with the CustomerName field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ListOrders200ResponseDataInner) GetCustomerNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.CustomerName.Get(), o.CustomerName.IsSet()
}

// HasCustomerName returns a boolean if a field has been set.
func (o *ListOrders200ResponseDataInner) HasCustomerName() bool {
	if o != nil && o.CustomerName.IsSet() {
		return true
	}

	return false
}

// SetCustomerName gets a reference to the given NullableString and assigns it to the CustomerName field.
func (o *ListOrders200ResponseDataInner) SetCustomerName(v string) {
	o.CustomerName.Set(&v)
}
// SetCustomerNameNil sets the value for CustomerName to be an explicit nil
func (o *ListOrders200ResponseDataInner) SetCustomerNameNil() {
	o.CustomerName.Set(nil)
}

// UnsetCustomerName ensures that no value is present for CustomerName, not even an explicit nil
func (o *ListOrders200ResponseDataInner) UnsetCustomerName() {
	o.CustomerName.Unset()
}

// GetCustomerEmail returns the CustomerEmail field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ListOrders200ResponseDataInner) GetCustomerEmail() string {
	if o == nil || IsNil(o.CustomerEmail.Get()) {
		var ret string
		return ret
	}
	return *o.CustomerEmail.Get()
}

// GetCustomerEmailOk returns a tuple with the CustomerEmail field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ListOrders200ResponseDataInner) GetCustomerEmailOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.CustomerEmail.Get(), o.CustomerEmail.IsSet()
}

// HasCustomerEmail returns a boolean if a field has been set.
func (o *ListOrders200ResponseDataInner) HasCustomerEmail() bool {
	if o != nil && o.CustomerEmail.IsSet() {
		return true
	}

	return false
}

// SetCustomerEmail gets a reference to the given NullableString and assigns it to the CustomerEmail field.
func (o *ListOrders200ResponseDataInner) SetCustomerEmail(v string) {
	o.CustomerEmail.Set(&v)
}
// SetCustomerEmailNil sets the value for CustomerEmail to be an explicit nil
func (o *ListOrders200ResponseDataInner) SetCustomerEmailNil() {
	o.CustomerEmail.Set(nil)
}

// UnsetCustomerEmail ensures that no value is present for CustomerEmail, not even an explicit nil
func (o *ListOrders200ResponseDataInner) UnsetCustomerEmail() {
	o.CustomerEmail.Unset()
}

// GetStatus returns the Status field value
func (o *ListOrders200ResponseDataInner) GetStatus() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Status
}

// GetStatusOk returns a tuple with the Status field value
// and a boolean to check if the value has been set.
func (o *ListOrders200ResponseDataInner) GetStatusOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Status, true
}

// SetStatus sets field value
func (o *ListOrders200ResponseDataInner) SetStatus(v string) {
	o.Status = v
}

// GetBrandId returns the BrandId field value
// If the value is explicit nil, the zero value for string will be returned
func (o *ListOrders200ResponseDataInner) GetBrandId() string {
	if o == nil || o.BrandId.Get() == nil {
		var ret string
		return ret
	}

	return *o.BrandId.Get()
}

// GetBrandIdOk returns a tuple with the BrandId field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ListOrders200ResponseDataInner) GetBrandIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.BrandId.Get(), o.BrandId.IsSet()
}

// SetBrandId sets field value
func (o *ListOrders200ResponseDataInner) SetBrandId(v string) {
	o.BrandId.Set(&v)
}

// GetSubtotalAmount returns the SubtotalAmount field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ListOrders200ResponseDataInner) GetSubtotalAmount() float32 {
	if o == nil || IsNil(o.SubtotalAmount.Get()) {
		var ret float32
		return ret
	}
	return *o.SubtotalAmount.Get()
}

// GetSubtotalAmountOk returns a tuple with the SubtotalAmount field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ListOrders200ResponseDataInner) GetSubtotalAmountOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return o.SubtotalAmount.Get(), o.SubtotalAmount.IsSet()
}

// HasSubtotalAmount returns a boolean if a field has been set.
func (o *ListOrders200ResponseDataInner) HasSubtotalAmount() bool {
	if o != nil && o.SubtotalAmount.IsSet() {
		return true
	}

	return false
}

// SetSubtotalAmount gets a reference to the given NullableFloat32 and assigns it to the SubtotalAmount field.
func (o *ListOrders200ResponseDataInner) SetSubtotalAmount(v float32) {
	o.SubtotalAmount.Set(&v)
}
// SetSubtotalAmountNil sets the value for SubtotalAmount to be an explicit nil
func (o *ListOrders200ResponseDataInner) SetSubtotalAmountNil() {
	o.SubtotalAmount.Set(nil)
}

// UnsetSubtotalAmount ensures that no value is present for SubtotalAmount, not even an explicit nil
func (o *ListOrders200ResponseDataInner) UnsetSubtotalAmount() {
	o.SubtotalAmount.Unset()
}

// GetTotalAmount returns the TotalAmount field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ListOrders200ResponseDataInner) GetTotalAmount() float32 {
	if o == nil || IsNil(o.TotalAmount.Get()) {
		var ret float32
		return ret
	}
	return *o.TotalAmount.Get()
}

// GetTotalAmountOk returns a tuple with the TotalAmount field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ListOrders200ResponseDataInner) GetTotalAmountOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return o.TotalAmount.Get(), o.TotalAmount.IsSet()
}

// HasTotalAmount returns a boolean if a field has been set.
func (o *ListOrders200ResponseDataInner) HasTotalAmount() bool {
	if o != nil && o.TotalAmount.IsSet() {
		return true
	}

	return false
}

// SetTotalAmount gets a reference to the given NullableFloat32 and assigns it to the TotalAmount field.
func (o *ListOrders200ResponseDataInner) SetTotalAmount(v float32) {
	o.TotalAmount.Set(&v)
}
// SetTotalAmountNil sets the value for TotalAmount to be an explicit nil
func (o *ListOrders200ResponseDataInner) SetTotalAmountNil() {
	o.TotalAmount.Set(nil)
}

// UnsetTotalAmount ensures that no value is present for TotalAmount, not even an explicit nil
func (o *ListOrders200ResponseDataInner) UnsetTotalAmount() {
	o.TotalAmount.Unset()
}

// GetCurrency returns the Currency field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ListOrders200ResponseDataInner) GetCurrency() string {
	if o == nil || IsNil(o.Currency.Get()) {
		var ret string
		return ret
	}
	return *o.Currency.Get()
}

// GetCurrencyOk returns a tuple with the Currency field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ListOrders200ResponseDataInner) GetCurrencyOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Currency.Get(), o.Currency.IsSet()
}

// HasCurrency returns a boolean if a field has been set.
func (o *ListOrders200ResponseDataInner) HasCurrency() bool {
	if o != nil && o.Currency.IsSet() {
		return true
	}

	return false
}

// SetCurrency gets a reference to the given NullableString and assigns it to the Currency field.
func (o *ListOrders200ResponseDataInner) SetCurrency(v string) {
	o.Currency.Set(&v)
}
// SetCurrencyNil sets the value for Currency to be an explicit nil
func (o *ListOrders200ResponseDataInner) SetCurrencyNil() {
	o.Currency.Set(nil)
}

// UnsetCurrency ensures that no value is present for Currency, not even an explicit nil
func (o *ListOrders200ResponseDataInner) UnsetCurrency() {
	o.Currency.Unset()
}

// GetShipmentCount returns the ShipmentCount field value
func (o *ListOrders200ResponseDataInner) GetShipmentCount() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.ShipmentCount
}

// GetShipmentCountOk returns a tuple with the ShipmentCount field value
// and a boolean to check if the value has been set.
func (o *ListOrders200ResponseDataInner) GetShipmentCountOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ShipmentCount, true
}

// SetShipmentCount sets field value
func (o *ListOrders200ResponseDataInner) SetShipmentCount(v int32) {
	o.ShipmentCount = v
}

// GetOrderChannel returns the OrderChannel field value
func (o *ListOrders200ResponseDataInner) GetOrderChannel() ListOrders200ResponseDataInnerOrderChannel {
	if o == nil {
		var ret ListOrders200ResponseDataInnerOrderChannel
		return ret
	}

	return o.OrderChannel
}

// GetOrderChannelOk returns a tuple with the OrderChannel field value
// and a boolean to check if the value has been set.
func (o *ListOrders200ResponseDataInner) GetOrderChannelOk() (*ListOrders200ResponseDataInnerOrderChannel, bool) {
	if o == nil {
		return nil, false
	}
	return &o.OrderChannel, true
}

// SetOrderChannel sets field value
func (o *ListOrders200ResponseDataInner) SetOrderChannel(v ListOrders200ResponseDataInnerOrderChannel) {
	o.OrderChannel = v
}

// GetCreatedAt returns the CreatedAt field value
func (o *ListOrders200ResponseDataInner) GetCreatedAt() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value
// and a boolean to check if the value has been set.
func (o *ListOrders200ResponseDataInner) GetCreatedAtOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CreatedAt, true
}

// SetCreatedAt sets field value
func (o *ListOrders200ResponseDataInner) SetCreatedAt(v string) {
	o.CreatedAt = v
}

// GetUpdatedAt returns the UpdatedAt field value
func (o *ListOrders200ResponseDataInner) GetUpdatedAt() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.UpdatedAt
}

// GetUpdatedAtOk returns a tuple with the UpdatedAt field value
// and a boolean to check if the value has been set.
func (o *ListOrders200ResponseDataInner) GetUpdatedAtOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.UpdatedAt, true
}

// SetUpdatedAt sets field value
func (o *ListOrders200ResponseDataInner) SetUpdatedAt(v string) {
	o.UpdatedAt = v
}

func (o ListOrders200ResponseDataInner) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ListOrders200ResponseDataInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["orderNumber"] = o.OrderNumber
	if o.CustomerName.IsSet() {
		toSerialize["customerName"] = o.CustomerName.Get()
	}
	if o.CustomerEmail.IsSet() {
		toSerialize["customerEmail"] = o.CustomerEmail.Get()
	}
	toSerialize["status"] = o.Status
	toSerialize["brandId"] = o.BrandId.Get()
	if o.SubtotalAmount.IsSet() {
		toSerialize["subtotalAmount"] = o.SubtotalAmount.Get()
	}
	if o.TotalAmount.IsSet() {
		toSerialize["totalAmount"] = o.TotalAmount.Get()
	}
	if o.Currency.IsSet() {
		toSerialize["currency"] = o.Currency.Get()
	}
	toSerialize["shipmentCount"] = o.ShipmentCount
	toSerialize["orderChannel"] = o.OrderChannel
	toSerialize["createdAt"] = o.CreatedAt
	toSerialize["updatedAt"] = o.UpdatedAt
	return toSerialize, nil
}

func (o *ListOrders200ResponseDataInner) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"orderNumber",
		"status",
		"brandId",
		"shipmentCount",
		"orderChannel",
		"createdAt",
		"updatedAt",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varListOrders200ResponseDataInner := _ListOrders200ResponseDataInner{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varListOrders200ResponseDataInner)

	if err != nil {
		return err
	}

	*o = ListOrders200ResponseDataInner(varListOrders200ResponseDataInner)

	return err
}

type NullableListOrders200ResponseDataInner struct {
	value *ListOrders200ResponseDataInner
	isSet bool
}

func (v NullableListOrders200ResponseDataInner) Get() *ListOrders200ResponseDataInner {
	return v.value
}

func (v *NullableListOrders200ResponseDataInner) Set(val *ListOrders200ResponseDataInner) {
	v.value = val
	v.isSet = true
}

func (v NullableListOrders200ResponseDataInner) IsSet() bool {
	return v.isSet
}

func (v *NullableListOrders200ResponseDataInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableListOrders200ResponseDataInner(val *ListOrders200ResponseDataInner) *NullableListOrders200ResponseDataInner {
	return &NullableListOrders200ResponseDataInner{value: val, isSet: true}
}

func (v NullableListOrders200ResponseDataInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableListOrders200ResponseDataInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


