/*
Zippendo Public API

Public API documentation for Zippendo. Authenticate using your API token (Bearer token prefixed with zipp_).

API version: 1.0.0
Contact: support@zippendo.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package zippendo

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the CreateShippingQuote200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateShippingQuote200Response{}

// CreateShippingQuote200Response struct for CreateShippingQuote200Response
type CreateShippingQuote200Response struct {
	// Available shipping rates
	Rates []CreateShippingQuote200ResponseRatesInner `json:"rates"`
}

type _CreateShippingQuote200Response CreateShippingQuote200Response

// NewCreateShippingQuote200Response instantiates a new CreateShippingQuote200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateShippingQuote200Response(rates []CreateShippingQuote200ResponseRatesInner) *CreateShippingQuote200Response {
	this := CreateShippingQuote200Response{}
	this.Rates = rates
	return &this
}

// NewCreateShippingQuote200ResponseWithDefaults instantiates a new CreateShippingQuote200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateShippingQuote200ResponseWithDefaults() *CreateShippingQuote200Response {
	this := CreateShippingQuote200Response{}
	return &this
}

// GetRates returns the Rates field value
func (o *CreateShippingQuote200Response) GetRates() []CreateShippingQuote200ResponseRatesInner {
	if o == nil {
		var ret []CreateShippingQuote200ResponseRatesInner
		return ret
	}

	return o.Rates
}

// GetRatesOk returns a tuple with the Rates field value
// and a boolean to check if the value has been set.
func (o *CreateShippingQuote200Response) GetRatesOk() ([]CreateShippingQuote200ResponseRatesInner, bool) {
	if o == nil {
		return nil, false
	}
	return o.Rates, true
}

// SetRates sets field value
func (o *CreateShippingQuote200Response) SetRates(v []CreateShippingQuote200ResponseRatesInner) {
	o.Rates = v
}

func (o CreateShippingQuote200Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateShippingQuote200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["rates"] = o.Rates
	return toSerialize, nil
}

func (o *CreateShippingQuote200Response) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"rates",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCreateShippingQuote200Response := _CreateShippingQuote200Response{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varCreateShippingQuote200Response)

	if err != nil {
		return err
	}

	*o = CreateShippingQuote200Response(varCreateShippingQuote200Response)

	return err
}

type NullableCreateShippingQuote200Response struct {
	value *CreateShippingQuote200Response
	isSet bool
}

func (v NullableCreateShippingQuote200Response) Get() *CreateShippingQuote200Response {
	return v.value
}

func (v *NullableCreateShippingQuote200Response) Set(val *CreateShippingQuote200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateShippingQuote200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateShippingQuote200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateShippingQuote200Response(val *CreateShippingQuote200Response) *NullableCreateShippingQuote200Response {
	return &NullableCreateShippingQuote200Response{value: val, isSet: true}
}

func (v NullableCreateShippingQuote200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateShippingQuote200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


