/*
Zippendo Public API

Public API documentation for Zippendo. Authenticate using your API token (Bearer token prefixed with zipp_).  **Brands (sub-accounts).** An organization can be split into brands, each keeping its own orders, shipments and configuration separate. There are two ways to scope requests to one brand, and NEITHER changes any request body:  1. **Bind the token.** Create an API token with a `brandId` and every request it makes is confined    to that brand — reads filtered, writes stamped. This is the recommended way to give a single    brand's team its own credential. 2. **Send the `X-Zippendo-Brand` header.** An organization-wide token can scope an individual    request by sending the brand's id or slug in this header. Most SDKs let you set it once on the    client so every call inherits it.  A brand-bound token that receives an `X-Zippendo-Brand` header naming a different brand is rejected with `403 BRAND_ACCESS_DENIED` — the binding is never widened. Omit both and requests cover the whole organization, which is the behaviour of every existing token.  Records that belong to no brand carry `brandId: null`. Configuration (carriers, shipping rules, addresses) with a null brand is organization-wide and remains visible inside every brand; orders and shipments with a null brand are only visible organization-wide.  Brands themselves are managed under the **Brands** tag. Retiring a brand is done with `POST /orgs/{orgId}/brands/{brandId}/archive` — permanent deletion is a dashboard-only action, since it is refused while any order, shipment, member or token still references the brand. Brands require a plan that includes them; creating one beyond your plan's limit returns `403`.

API version: 1.0.0
Contact: support@zippendo.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package zippendo

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the BatchSplitShipmentRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &BatchSplitShipmentRequest{}

// BatchSplitShipmentRequest struct for BatchSplitShipmentRequest
type BatchSplitShipmentRequest struct {
	// Parcel whose order lines are split across new shipments.
	ParcelId string `json:"parcelId"`
	// New shipments to create from the split parcel.
	Shipments []BatchSplitShipmentRequestShipmentsInner `json:"shipments"`
	// Carrier for all new shipments. Copied from the original if omitted.
	CarrierId *string `json:"carrierId,omitempty"`
	// Carrier product for all new shipments. Copied from the original if omitted.
	ProductId *string `json:"productId,omitempty"`
	// Service codes for all new shipments. Copied from the original if omitted.
	Services []string `json:"services,omitempty"`
	// Carrier-specific parameters for all new shipments.
	AdditionalParameters map[string]interface{} `json:"additionalParameters,omitempty"`
}

type _BatchSplitShipmentRequest BatchSplitShipmentRequest

// NewBatchSplitShipmentRequest instantiates a new BatchSplitShipmentRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewBatchSplitShipmentRequest(parcelId string, shipments []BatchSplitShipmentRequestShipmentsInner) *BatchSplitShipmentRequest {
	this := BatchSplitShipmentRequest{}
	this.ParcelId = parcelId
	this.Shipments = shipments
	return &this
}

// NewBatchSplitShipmentRequestWithDefaults instantiates a new BatchSplitShipmentRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewBatchSplitShipmentRequestWithDefaults() *BatchSplitShipmentRequest {
	this := BatchSplitShipmentRequest{}
	return &this
}

// GetParcelId returns the ParcelId field value
func (o *BatchSplitShipmentRequest) GetParcelId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ParcelId
}

// GetParcelIdOk returns a tuple with the ParcelId field value
// and a boolean to check if the value has been set.
func (o *BatchSplitShipmentRequest) GetParcelIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ParcelId, true
}

// SetParcelId sets field value
func (o *BatchSplitShipmentRequest) SetParcelId(v string) {
	o.ParcelId = v
}

// GetShipments returns the Shipments field value
func (o *BatchSplitShipmentRequest) GetShipments() []BatchSplitShipmentRequestShipmentsInner {
	if o == nil {
		var ret []BatchSplitShipmentRequestShipmentsInner
		return ret
	}

	return o.Shipments
}

// GetShipmentsOk returns a tuple with the Shipments field value
// and a boolean to check if the value has been set.
func (o *BatchSplitShipmentRequest) GetShipmentsOk() ([]BatchSplitShipmentRequestShipmentsInner, bool) {
	if o == nil {
		return nil, false
	}
	return o.Shipments, true
}

// SetShipments sets field value
func (o *BatchSplitShipmentRequest) SetShipments(v []BatchSplitShipmentRequestShipmentsInner) {
	o.Shipments = v
}

// GetCarrierId returns the CarrierId field value if set, zero value otherwise.
func (o *BatchSplitShipmentRequest) GetCarrierId() string {
	if o == nil || IsNil(o.CarrierId) {
		var ret string
		return ret
	}
	return *o.CarrierId
}

// GetCarrierIdOk returns a tuple with the CarrierId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BatchSplitShipmentRequest) GetCarrierIdOk() (*string, bool) {
	if o == nil || IsNil(o.CarrierId) {
		return nil, false
	}
	return o.CarrierId, true
}

// HasCarrierId returns a boolean if a field has been set.
func (o *BatchSplitShipmentRequest) HasCarrierId() bool {
	if o != nil && !IsNil(o.CarrierId) {
		return true
	}

	return false
}

// SetCarrierId gets a reference to the given string and assigns it to the CarrierId field.
func (o *BatchSplitShipmentRequest) SetCarrierId(v string) {
	o.CarrierId = &v
}

// GetProductId returns the ProductId field value if set, zero value otherwise.
func (o *BatchSplitShipmentRequest) GetProductId() string {
	if o == nil || IsNil(o.ProductId) {
		var ret string
		return ret
	}
	return *o.ProductId
}

// GetProductIdOk returns a tuple with the ProductId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BatchSplitShipmentRequest) GetProductIdOk() (*string, bool) {
	if o == nil || IsNil(o.ProductId) {
		return nil, false
	}
	return o.ProductId, true
}

// HasProductId returns a boolean if a field has been set.
func (o *BatchSplitShipmentRequest) HasProductId() bool {
	if o != nil && !IsNil(o.ProductId) {
		return true
	}

	return false
}

// SetProductId gets a reference to the given string and assigns it to the ProductId field.
func (o *BatchSplitShipmentRequest) SetProductId(v string) {
	o.ProductId = &v
}

// GetServices returns the Services field value if set, zero value otherwise.
func (o *BatchSplitShipmentRequest) GetServices() []string {
	if o == nil || IsNil(o.Services) {
		var ret []string
		return ret
	}
	return o.Services
}

// GetServicesOk returns a tuple with the Services field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BatchSplitShipmentRequest) GetServicesOk() ([]string, bool) {
	if o == nil || IsNil(o.Services) {
		return nil, false
	}
	return o.Services, true
}

// HasServices returns a boolean if a field has been set.
func (o *BatchSplitShipmentRequest) HasServices() bool {
	if o != nil && !IsNil(o.Services) {
		return true
	}

	return false
}

// SetServices gets a reference to the given []string and assigns it to the Services field.
func (o *BatchSplitShipmentRequest) SetServices(v []string) {
	o.Services = v
}

// GetAdditionalParameters returns the AdditionalParameters field value if set, zero value otherwise.
func (o *BatchSplitShipmentRequest) GetAdditionalParameters() map[string]interface{} {
	if o == nil || IsNil(o.AdditionalParameters) {
		var ret map[string]interface{}
		return ret
	}
	return o.AdditionalParameters
}

// GetAdditionalParametersOk returns a tuple with the AdditionalParameters field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BatchSplitShipmentRequest) GetAdditionalParametersOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.AdditionalParameters) {
		return map[string]interface{}{}, false
	}
	return o.AdditionalParameters, true
}

// HasAdditionalParameters returns a boolean if a field has been set.
func (o *BatchSplitShipmentRequest) HasAdditionalParameters() bool {
	if o != nil && !IsNil(o.AdditionalParameters) {
		return true
	}

	return false
}

// SetAdditionalParameters gets a reference to the given map[string]interface{} and assigns it to the AdditionalParameters field.
func (o *BatchSplitShipmentRequest) SetAdditionalParameters(v map[string]interface{}) {
	o.AdditionalParameters = v
}

func (o BatchSplitShipmentRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o BatchSplitShipmentRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["parcelId"] = o.ParcelId
	toSerialize["shipments"] = o.Shipments
	if !IsNil(o.CarrierId) {
		toSerialize["carrierId"] = o.CarrierId
	}
	if !IsNil(o.ProductId) {
		toSerialize["productId"] = o.ProductId
	}
	if !IsNil(o.Services) {
		toSerialize["services"] = o.Services
	}
	if !IsNil(o.AdditionalParameters) {
		toSerialize["additionalParameters"] = o.AdditionalParameters
	}
	return toSerialize, nil
}

func (o *BatchSplitShipmentRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"parcelId",
		"shipments",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varBatchSplitShipmentRequest := _BatchSplitShipmentRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varBatchSplitShipmentRequest)

	if err != nil {
		return err
	}

	*o = BatchSplitShipmentRequest(varBatchSplitShipmentRequest)

	return err
}

type NullableBatchSplitShipmentRequest struct {
	value *BatchSplitShipmentRequest
	isSet bool
}

func (v NullableBatchSplitShipmentRequest) Get() *BatchSplitShipmentRequest {
	return v.value
}

func (v *NullableBatchSplitShipmentRequest) Set(val *BatchSplitShipmentRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableBatchSplitShipmentRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableBatchSplitShipmentRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableBatchSplitShipmentRequest(val *BatchSplitShipmentRequest) *NullableBatchSplitShipmentRequest {
	return &NullableBatchSplitShipmentRequest{value: val, isSet: true}
}

func (v NullableBatchSplitShipmentRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableBatchSplitShipmentRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


