/*
Zippendo Public API

Public API documentation for Zippendo. Authenticate using your API token (Bearer token prefixed with zipp_).

API version: 1.0.0
Contact: support@zippendo.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package zippendo

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the CreateShippingRuleRequestAdditionalParametersAnyOfInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateShippingRuleRequestAdditionalParametersAnyOfInner{}

// CreateShippingRuleRequestAdditionalParametersAnyOfInner struct for CreateShippingRuleRequestAdditionalParametersAnyOfInner
type CreateShippingRuleRequestAdditionalParametersAnyOfInner struct {
	// Carrier parameter key
	Name string `json:"name"`
	// Parameter value (stringified)
	Val string `json:"val"`
}

type _CreateShippingRuleRequestAdditionalParametersAnyOfInner CreateShippingRuleRequestAdditionalParametersAnyOfInner

// NewCreateShippingRuleRequestAdditionalParametersAnyOfInner instantiates a new CreateShippingRuleRequestAdditionalParametersAnyOfInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateShippingRuleRequestAdditionalParametersAnyOfInner(name string, val string) *CreateShippingRuleRequestAdditionalParametersAnyOfInner {
	this := CreateShippingRuleRequestAdditionalParametersAnyOfInner{}
	this.Name = name
	this.Val = val
	return &this
}

// NewCreateShippingRuleRequestAdditionalParametersAnyOfInnerWithDefaults instantiates a new CreateShippingRuleRequestAdditionalParametersAnyOfInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateShippingRuleRequestAdditionalParametersAnyOfInnerWithDefaults() *CreateShippingRuleRequestAdditionalParametersAnyOfInner {
	this := CreateShippingRuleRequestAdditionalParametersAnyOfInner{}
	return &this
}

// GetName returns the Name field value
func (o *CreateShippingRuleRequestAdditionalParametersAnyOfInner) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *CreateShippingRuleRequestAdditionalParametersAnyOfInner) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *CreateShippingRuleRequestAdditionalParametersAnyOfInner) SetName(v string) {
	o.Name = v
}

// GetVal returns the Val field value
func (o *CreateShippingRuleRequestAdditionalParametersAnyOfInner) GetVal() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Val
}

// GetValOk returns a tuple with the Val field value
// and a boolean to check if the value has been set.
func (o *CreateShippingRuleRequestAdditionalParametersAnyOfInner) GetValOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Val, true
}

// SetVal sets field value
func (o *CreateShippingRuleRequestAdditionalParametersAnyOfInner) SetVal(v string) {
	o.Val = v
}

func (o CreateShippingRuleRequestAdditionalParametersAnyOfInner) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateShippingRuleRequestAdditionalParametersAnyOfInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["name"] = o.Name
	toSerialize["val"] = o.Val
	return toSerialize, nil
}

func (o *CreateShippingRuleRequestAdditionalParametersAnyOfInner) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"name",
		"val",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCreateShippingRuleRequestAdditionalParametersAnyOfInner := _CreateShippingRuleRequestAdditionalParametersAnyOfInner{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varCreateShippingRuleRequestAdditionalParametersAnyOfInner)

	if err != nil {
		return err
	}

	*o = CreateShippingRuleRequestAdditionalParametersAnyOfInner(varCreateShippingRuleRequestAdditionalParametersAnyOfInner)

	return err
}

type NullableCreateShippingRuleRequestAdditionalParametersAnyOfInner struct {
	value *CreateShippingRuleRequestAdditionalParametersAnyOfInner
	isSet bool
}

func (v NullableCreateShippingRuleRequestAdditionalParametersAnyOfInner) Get() *CreateShippingRuleRequestAdditionalParametersAnyOfInner {
	return v.value
}

func (v *NullableCreateShippingRuleRequestAdditionalParametersAnyOfInner) Set(val *CreateShippingRuleRequestAdditionalParametersAnyOfInner) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateShippingRuleRequestAdditionalParametersAnyOfInner) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateShippingRuleRequestAdditionalParametersAnyOfInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateShippingRuleRequestAdditionalParametersAnyOfInner(val *CreateShippingRuleRequestAdditionalParametersAnyOfInner) *NullableCreateShippingRuleRequestAdditionalParametersAnyOfInner {
	return &NullableCreateShippingRuleRequestAdditionalParametersAnyOfInner{value: val, isSet: true}
}

func (v NullableCreateShippingRuleRequestAdditionalParametersAnyOfInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateShippingRuleRequestAdditionalParametersAnyOfInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


