/*
Zippendo Public API

Public API documentation for Zippendo. Authenticate using your API token (Bearer token prefixed with zipp_).  **Brands (sub-accounts).** An organization can be split into brands, each keeping its own orders, shipments and configuration separate. There are two ways to scope requests to one brand, and NEITHER changes any request body:  1. **Bind the token.** Create an API token with a `brandId` and every request it makes is confined    to that brand — reads filtered, writes stamped. This is the recommended way to give a single    brand's team its own credential. 2. **Send the `X-Zippendo-Brand` header.** An organization-wide token can scope an individual    request by sending the brand's id or slug in this header. Most SDKs let you set it once on the    client so every call inherits it.  A brand-bound token that receives an `X-Zippendo-Brand` header naming a different brand is rejected with `403 BRAND_ACCESS_DENIED` — the binding is never widened. Omit both and requests cover the whole organization, which is the behaviour of every existing token.  Records that belong to no brand carry `brandId: null`. Configuration (carriers, shipping rules, addresses) with a null brand is organization-wide and remains visible inside every brand; orders and shipments with a null brand are only visible organization-wide.  Brands themselves are managed under the **Brands** tag. Retiring a brand is done with `POST /orgs/{orgId}/brands/{brandId}/archive` — permanent deletion is a dashboard-only action, since it is refused while any order, shipment, member or token still references the brand. Brands require a plan that includes them; creating one beyond your plan's limit returns `403`.

API version: 1.0.0
Contact: support@zippendo.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package zippendo

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the UpdateApiTokenRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UpdateApiTokenRequest{}

// UpdateApiTokenRequest struct for UpdateApiTokenRequest
type UpdateApiTokenRequest struct {
	// New token name
	Name string `json:"name"`
}

type _UpdateApiTokenRequest UpdateApiTokenRequest

// NewUpdateApiTokenRequest instantiates a new UpdateApiTokenRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUpdateApiTokenRequest(name string) *UpdateApiTokenRequest {
	this := UpdateApiTokenRequest{}
	this.Name = name
	return &this
}

// NewUpdateApiTokenRequestWithDefaults instantiates a new UpdateApiTokenRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUpdateApiTokenRequestWithDefaults() *UpdateApiTokenRequest {
	this := UpdateApiTokenRequest{}
	return &this
}

// GetName returns the Name field value
func (o *UpdateApiTokenRequest) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *UpdateApiTokenRequest) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *UpdateApiTokenRequest) SetName(v string) {
	o.Name = v
}

func (o UpdateApiTokenRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UpdateApiTokenRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["name"] = o.Name
	return toSerialize, nil
}

func (o *UpdateApiTokenRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"name",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varUpdateApiTokenRequest := _UpdateApiTokenRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varUpdateApiTokenRequest)

	if err != nil {
		return err
	}

	*o = UpdateApiTokenRequest(varUpdateApiTokenRequest)

	return err
}

type NullableUpdateApiTokenRequest struct {
	value *UpdateApiTokenRequest
	isSet bool
}

func (v NullableUpdateApiTokenRequest) Get() *UpdateApiTokenRequest {
	return v.value
}

func (v *NullableUpdateApiTokenRequest) Set(val *UpdateApiTokenRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableUpdateApiTokenRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableUpdateApiTokenRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUpdateApiTokenRequest(val *UpdateApiTokenRequest) *NullableUpdateApiTokenRequest {
	return &NullableUpdateApiTokenRequest{value: val, isSet: true}
}

func (v NullableUpdateApiTokenRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUpdateApiTokenRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


