/*
Zippendo Public API

Public API documentation for Zippendo. Authenticate using your API token (Bearer token prefixed with zipp_).

API version: 1.0.0
Contact: support@zippendo.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package zippendo

import (
	"encoding/json"
)

// checks if the UpdateOrgWebhookRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UpdateOrgWebhookRequest{}

// UpdateOrgWebhookRequest struct for UpdateOrgWebhookRequest
type UpdateOrgWebhookRequest struct {
	// Human-readable webhook name
	Name *string `json:"name,omitempty"`
	// Webhook endpoint URL
	Url *string `json:"url,omitempty"`
	// Events to subscribe to
	Events []string `json:"events,omitempty"`
	// Whether the webhook is active
	IsActive *bool `json:"isActive,omitempty"`
}

// NewUpdateOrgWebhookRequest instantiates a new UpdateOrgWebhookRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUpdateOrgWebhookRequest() *UpdateOrgWebhookRequest {
	this := UpdateOrgWebhookRequest{}
	return &this
}

// NewUpdateOrgWebhookRequestWithDefaults instantiates a new UpdateOrgWebhookRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUpdateOrgWebhookRequestWithDefaults() *UpdateOrgWebhookRequest {
	this := UpdateOrgWebhookRequest{}
	return &this
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *UpdateOrgWebhookRequest) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateOrgWebhookRequest) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *UpdateOrgWebhookRequest) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *UpdateOrgWebhookRequest) SetName(v string) {
	o.Name = &v
}

// GetUrl returns the Url field value if set, zero value otherwise.
func (o *UpdateOrgWebhookRequest) GetUrl() string {
	if o == nil || IsNil(o.Url) {
		var ret string
		return ret
	}
	return *o.Url
}

// GetUrlOk returns a tuple with the Url field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateOrgWebhookRequest) GetUrlOk() (*string, bool) {
	if o == nil || IsNil(o.Url) {
		return nil, false
	}
	return o.Url, true
}

// HasUrl returns a boolean if a field has been set.
func (o *UpdateOrgWebhookRequest) HasUrl() bool {
	if o != nil && !IsNil(o.Url) {
		return true
	}

	return false
}

// SetUrl gets a reference to the given string and assigns it to the Url field.
func (o *UpdateOrgWebhookRequest) SetUrl(v string) {
	o.Url = &v
}

// GetEvents returns the Events field value if set, zero value otherwise.
func (o *UpdateOrgWebhookRequest) GetEvents() []string {
	if o == nil || IsNil(o.Events) {
		var ret []string
		return ret
	}
	return o.Events
}

// GetEventsOk returns a tuple with the Events field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateOrgWebhookRequest) GetEventsOk() ([]string, bool) {
	if o == nil || IsNil(o.Events) {
		return nil, false
	}
	return o.Events, true
}

// HasEvents returns a boolean if a field has been set.
func (o *UpdateOrgWebhookRequest) HasEvents() bool {
	if o != nil && !IsNil(o.Events) {
		return true
	}

	return false
}

// SetEvents gets a reference to the given []string and assigns it to the Events field.
func (o *UpdateOrgWebhookRequest) SetEvents(v []string) {
	o.Events = v
}

// GetIsActive returns the IsActive field value if set, zero value otherwise.
func (o *UpdateOrgWebhookRequest) GetIsActive() bool {
	if o == nil || IsNil(o.IsActive) {
		var ret bool
		return ret
	}
	return *o.IsActive
}

// GetIsActiveOk returns a tuple with the IsActive field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateOrgWebhookRequest) GetIsActiveOk() (*bool, bool) {
	if o == nil || IsNil(o.IsActive) {
		return nil, false
	}
	return o.IsActive, true
}

// HasIsActive returns a boolean if a field has been set.
func (o *UpdateOrgWebhookRequest) HasIsActive() bool {
	if o != nil && !IsNil(o.IsActive) {
		return true
	}

	return false
}

// SetIsActive gets a reference to the given bool and assigns it to the IsActive field.
func (o *UpdateOrgWebhookRequest) SetIsActive(v bool) {
	o.IsActive = &v
}

func (o UpdateOrgWebhookRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UpdateOrgWebhookRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !IsNil(o.Url) {
		toSerialize["url"] = o.Url
	}
	if !IsNil(o.Events) {
		toSerialize["events"] = o.Events
	}
	if !IsNil(o.IsActive) {
		toSerialize["isActive"] = o.IsActive
	}
	return toSerialize, nil
}

type NullableUpdateOrgWebhookRequest struct {
	value *UpdateOrgWebhookRequest
	isSet bool
}

func (v NullableUpdateOrgWebhookRequest) Get() *UpdateOrgWebhookRequest {
	return v.value
}

func (v *NullableUpdateOrgWebhookRequest) Set(val *UpdateOrgWebhookRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableUpdateOrgWebhookRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableUpdateOrgWebhookRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUpdateOrgWebhookRequest(val *UpdateOrgWebhookRequest) *NullableUpdateOrgWebhookRequest {
	return &NullableUpdateOrgWebhookRequest{value: val, isSet: true}
}

func (v NullableUpdateOrgWebhookRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUpdateOrgWebhookRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


