/*
Zippendo Public API

Public API documentation for Zippendo. Authenticate using your API token (Bearer token prefixed with zipp_).

API version: 1.0.0
Contact: support@zippendo.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package zippendo

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the CreateShipment201ResponseLogsInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateShipment201ResponseLogsInner{}

// CreateShipment201ResponseLogsInner struct for CreateShipment201ResponseLogsInner
type CreateShipment201ResponseLogsInner struct {
	// Unique log entry identifier.
	Id string `json:"id"`
	// Direction of the logged request.
	Direction string `json:"direction"`
	// Captured request payload.
	Request interface{} `json:"request"`
	// Captured response payload.
	Response interface{} `json:"response,omitempty"`
	// HTTP status code of the response.
	StatusCode NullableFloat32 `json:"statusCode,omitempty"`
	// Error message if the request failed.
	Error NullableString `json:"error,omitempty"`
	// Request duration in milliseconds.
	Duration NullableFloat32 `json:"duration,omitempty"`
	// Timestamp when the log entry was created.
	CreatedAt string `json:"createdAt"`
}

type _CreateShipment201ResponseLogsInner CreateShipment201ResponseLogsInner

// NewCreateShipment201ResponseLogsInner instantiates a new CreateShipment201ResponseLogsInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateShipment201ResponseLogsInner(id string, direction string, request interface{}, createdAt string) *CreateShipment201ResponseLogsInner {
	this := CreateShipment201ResponseLogsInner{}
	this.Id = id
	this.Direction = direction
	this.Request = request
	this.CreatedAt = createdAt
	return &this
}

// NewCreateShipment201ResponseLogsInnerWithDefaults instantiates a new CreateShipment201ResponseLogsInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateShipment201ResponseLogsInnerWithDefaults() *CreateShipment201ResponseLogsInner {
	this := CreateShipment201ResponseLogsInner{}
	return &this
}

// GetId returns the Id field value
func (o *CreateShipment201ResponseLogsInner) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *CreateShipment201ResponseLogsInner) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *CreateShipment201ResponseLogsInner) SetId(v string) {
	o.Id = v
}

// GetDirection returns the Direction field value
func (o *CreateShipment201ResponseLogsInner) GetDirection() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Direction
}

// GetDirectionOk returns a tuple with the Direction field value
// and a boolean to check if the value has been set.
func (o *CreateShipment201ResponseLogsInner) GetDirectionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Direction, true
}

// SetDirection sets field value
func (o *CreateShipment201ResponseLogsInner) SetDirection(v string) {
	o.Direction = v
}

// GetRequest returns the Request field value
// If the value is explicit nil, the zero value for interface{} will be returned
func (o *CreateShipment201ResponseLogsInner) GetRequest() interface{} {
	if o == nil {
		var ret interface{}
		return ret
	}

	return o.Request
}

// GetRequestOk returns a tuple with the Request field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CreateShipment201ResponseLogsInner) GetRequestOk() (*interface{}, bool) {
	if o == nil || IsNil(o.Request) {
		return nil, false
	}
	return &o.Request, true
}

// SetRequest sets field value
func (o *CreateShipment201ResponseLogsInner) SetRequest(v interface{}) {
	o.Request = v
}

// GetResponse returns the Response field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CreateShipment201ResponseLogsInner) GetResponse() interface{} {
	if o == nil {
		var ret interface{}
		return ret
	}
	return o.Response
}

// GetResponseOk returns a tuple with the Response field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CreateShipment201ResponseLogsInner) GetResponseOk() (*interface{}, bool) {
	if o == nil || IsNil(o.Response) {
		return nil, false
	}
	return &o.Response, true
}

// HasResponse returns a boolean if a field has been set.
func (o *CreateShipment201ResponseLogsInner) HasResponse() bool {
	if o != nil && !IsNil(o.Response) {
		return true
	}

	return false
}

// SetResponse gets a reference to the given interface{} and assigns it to the Response field.
func (o *CreateShipment201ResponseLogsInner) SetResponse(v interface{}) {
	o.Response = v
}

// GetStatusCode returns the StatusCode field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CreateShipment201ResponseLogsInner) GetStatusCode() float32 {
	if o == nil || IsNil(o.StatusCode.Get()) {
		var ret float32
		return ret
	}
	return *o.StatusCode.Get()
}

// GetStatusCodeOk returns a tuple with the StatusCode field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CreateShipment201ResponseLogsInner) GetStatusCodeOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return o.StatusCode.Get(), o.StatusCode.IsSet()
}

// HasStatusCode returns a boolean if a field has been set.
func (o *CreateShipment201ResponseLogsInner) HasStatusCode() bool {
	if o != nil && o.StatusCode.IsSet() {
		return true
	}

	return false
}

// SetStatusCode gets a reference to the given NullableFloat32 and assigns it to the StatusCode field.
func (o *CreateShipment201ResponseLogsInner) SetStatusCode(v float32) {
	o.StatusCode.Set(&v)
}
// SetStatusCodeNil sets the value for StatusCode to be an explicit nil
func (o *CreateShipment201ResponseLogsInner) SetStatusCodeNil() {
	o.StatusCode.Set(nil)
}

// UnsetStatusCode ensures that no value is present for StatusCode, not even an explicit nil
func (o *CreateShipment201ResponseLogsInner) UnsetStatusCode() {
	o.StatusCode.Unset()
}

// GetError returns the Error field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CreateShipment201ResponseLogsInner) GetError() string {
	if o == nil || IsNil(o.Error.Get()) {
		var ret string
		return ret
	}
	return *o.Error.Get()
}

// GetErrorOk returns a tuple with the Error field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CreateShipment201ResponseLogsInner) GetErrorOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Error.Get(), o.Error.IsSet()
}

// HasError returns a boolean if a field has been set.
func (o *CreateShipment201ResponseLogsInner) HasError() bool {
	if o != nil && o.Error.IsSet() {
		return true
	}

	return false
}

// SetError gets a reference to the given NullableString and assigns it to the Error field.
func (o *CreateShipment201ResponseLogsInner) SetError(v string) {
	o.Error.Set(&v)
}
// SetErrorNil sets the value for Error to be an explicit nil
func (o *CreateShipment201ResponseLogsInner) SetErrorNil() {
	o.Error.Set(nil)
}

// UnsetError ensures that no value is present for Error, not even an explicit nil
func (o *CreateShipment201ResponseLogsInner) UnsetError() {
	o.Error.Unset()
}

// GetDuration returns the Duration field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CreateShipment201ResponseLogsInner) GetDuration() float32 {
	if o == nil || IsNil(o.Duration.Get()) {
		var ret float32
		return ret
	}
	return *o.Duration.Get()
}

// GetDurationOk returns a tuple with the Duration field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CreateShipment201ResponseLogsInner) GetDurationOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return o.Duration.Get(), o.Duration.IsSet()
}

// HasDuration returns a boolean if a field has been set.
func (o *CreateShipment201ResponseLogsInner) HasDuration() bool {
	if o != nil && o.Duration.IsSet() {
		return true
	}

	return false
}

// SetDuration gets a reference to the given NullableFloat32 and assigns it to the Duration field.
func (o *CreateShipment201ResponseLogsInner) SetDuration(v float32) {
	o.Duration.Set(&v)
}
// SetDurationNil sets the value for Duration to be an explicit nil
func (o *CreateShipment201ResponseLogsInner) SetDurationNil() {
	o.Duration.Set(nil)
}

// UnsetDuration ensures that no value is present for Duration, not even an explicit nil
func (o *CreateShipment201ResponseLogsInner) UnsetDuration() {
	o.Duration.Unset()
}

// GetCreatedAt returns the CreatedAt field value
func (o *CreateShipment201ResponseLogsInner) GetCreatedAt() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value
// and a boolean to check if the value has been set.
func (o *CreateShipment201ResponseLogsInner) GetCreatedAtOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CreatedAt, true
}

// SetCreatedAt sets field value
func (o *CreateShipment201ResponseLogsInner) SetCreatedAt(v string) {
	o.CreatedAt = v
}

func (o CreateShipment201ResponseLogsInner) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateShipment201ResponseLogsInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["direction"] = o.Direction
	if o.Request != nil {
		toSerialize["request"] = o.Request
	}
	if o.Response != nil {
		toSerialize["response"] = o.Response
	}
	if o.StatusCode.IsSet() {
		toSerialize["statusCode"] = o.StatusCode.Get()
	}
	if o.Error.IsSet() {
		toSerialize["error"] = o.Error.Get()
	}
	if o.Duration.IsSet() {
		toSerialize["duration"] = o.Duration.Get()
	}
	toSerialize["createdAt"] = o.CreatedAt
	return toSerialize, nil
}

func (o *CreateShipment201ResponseLogsInner) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"direction",
		"request",
		"createdAt",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCreateShipment201ResponseLogsInner := _CreateShipment201ResponseLogsInner{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varCreateShipment201ResponseLogsInner)

	if err != nil {
		return err
	}

	*o = CreateShipment201ResponseLogsInner(varCreateShipment201ResponseLogsInner)

	return err
}

type NullableCreateShipment201ResponseLogsInner struct {
	value *CreateShipment201ResponseLogsInner
	isSet bool
}

func (v NullableCreateShipment201ResponseLogsInner) Get() *CreateShipment201ResponseLogsInner {
	return v.value
}

func (v *NullableCreateShipment201ResponseLogsInner) Set(val *CreateShipment201ResponseLogsInner) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateShipment201ResponseLogsInner) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateShipment201ResponseLogsInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateShipment201ResponseLogsInner(val *CreateShipment201ResponseLogsInner) *NullableCreateShipment201ResponseLogsInner {
	return &NullableCreateShipment201ResponseLogsInner{value: val, isSet: true}
}

func (v NullableCreateShipment201ResponseLogsInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateShipment201ResponseLogsInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


