/*
Zippendo Public API

Public API documentation for Zippendo. Authenticate using your API token (Bearer token prefixed with zipp_).

API version: 1.0.0
Contact: support@zippendo.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package zippendo

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the CreateShippingQuoteRequestItemsInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateShippingQuoteRequestItemsInner{}

// CreateShippingQuoteRequestItemsInner struct for CreateShippingQuoteRequestItemsInner
type CreateShippingQuoteRequestItemsInner struct {
	// Item name
	Name string `json:"name"`
	// SKU identifier
	Sku NullableString `json:"sku,omitempty"`
	// Quantity
	Quantity int32 `json:"quantity"`
	// Weight in grams
	Grams float32 `json:"grams"`
	// Price in cents
	Price float32 `json:"price"`
	// Product ID
	ProductId NullableString `json:"productId,omitempty"`
	// Variant ID
	VariantId NullableString `json:"variantId,omitempty"`
}

type _CreateShippingQuoteRequestItemsInner CreateShippingQuoteRequestItemsInner

// NewCreateShippingQuoteRequestItemsInner instantiates a new CreateShippingQuoteRequestItemsInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateShippingQuoteRequestItemsInner(name string, quantity int32, grams float32, price float32) *CreateShippingQuoteRequestItemsInner {
	this := CreateShippingQuoteRequestItemsInner{}
	this.Name = name
	this.Quantity = quantity
	this.Grams = grams
	this.Price = price
	return &this
}

// NewCreateShippingQuoteRequestItemsInnerWithDefaults instantiates a new CreateShippingQuoteRequestItemsInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateShippingQuoteRequestItemsInnerWithDefaults() *CreateShippingQuoteRequestItemsInner {
	this := CreateShippingQuoteRequestItemsInner{}
	return &this
}

// GetName returns the Name field value
func (o *CreateShippingQuoteRequestItemsInner) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *CreateShippingQuoteRequestItemsInner) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *CreateShippingQuoteRequestItemsInner) SetName(v string) {
	o.Name = v
}

// GetSku returns the Sku field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CreateShippingQuoteRequestItemsInner) GetSku() string {
	if o == nil || IsNil(o.Sku.Get()) {
		var ret string
		return ret
	}
	return *o.Sku.Get()
}

// GetSkuOk returns a tuple with the Sku field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CreateShippingQuoteRequestItemsInner) GetSkuOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Sku.Get(), o.Sku.IsSet()
}

// HasSku returns a boolean if a field has been set.
func (o *CreateShippingQuoteRequestItemsInner) HasSku() bool {
	if o != nil && o.Sku.IsSet() {
		return true
	}

	return false
}

// SetSku gets a reference to the given NullableString and assigns it to the Sku field.
func (o *CreateShippingQuoteRequestItemsInner) SetSku(v string) {
	o.Sku.Set(&v)
}
// SetSkuNil sets the value for Sku to be an explicit nil
func (o *CreateShippingQuoteRequestItemsInner) SetSkuNil() {
	o.Sku.Set(nil)
}

// UnsetSku ensures that no value is present for Sku, not even an explicit nil
func (o *CreateShippingQuoteRequestItemsInner) UnsetSku() {
	o.Sku.Unset()
}

// GetQuantity returns the Quantity field value
func (o *CreateShippingQuoteRequestItemsInner) GetQuantity() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Quantity
}

// GetQuantityOk returns a tuple with the Quantity field value
// and a boolean to check if the value has been set.
func (o *CreateShippingQuoteRequestItemsInner) GetQuantityOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Quantity, true
}

// SetQuantity sets field value
func (o *CreateShippingQuoteRequestItemsInner) SetQuantity(v int32) {
	o.Quantity = v
}

// GetGrams returns the Grams field value
func (o *CreateShippingQuoteRequestItemsInner) GetGrams() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.Grams
}

// GetGramsOk returns a tuple with the Grams field value
// and a boolean to check if the value has been set.
func (o *CreateShippingQuoteRequestItemsInner) GetGramsOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Grams, true
}

// SetGrams sets field value
func (o *CreateShippingQuoteRequestItemsInner) SetGrams(v float32) {
	o.Grams = v
}

// GetPrice returns the Price field value
func (o *CreateShippingQuoteRequestItemsInner) GetPrice() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.Price
}

// GetPriceOk returns a tuple with the Price field value
// and a boolean to check if the value has been set.
func (o *CreateShippingQuoteRequestItemsInner) GetPriceOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Price, true
}

// SetPrice sets field value
func (o *CreateShippingQuoteRequestItemsInner) SetPrice(v float32) {
	o.Price = v
}

// GetProductId returns the ProductId field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CreateShippingQuoteRequestItemsInner) GetProductId() string {
	if o == nil || IsNil(o.ProductId.Get()) {
		var ret string
		return ret
	}
	return *o.ProductId.Get()
}

// GetProductIdOk returns a tuple with the ProductId field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CreateShippingQuoteRequestItemsInner) GetProductIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.ProductId.Get(), o.ProductId.IsSet()
}

// HasProductId returns a boolean if a field has been set.
func (o *CreateShippingQuoteRequestItemsInner) HasProductId() bool {
	if o != nil && o.ProductId.IsSet() {
		return true
	}

	return false
}

// SetProductId gets a reference to the given NullableString and assigns it to the ProductId field.
func (o *CreateShippingQuoteRequestItemsInner) SetProductId(v string) {
	o.ProductId.Set(&v)
}
// SetProductIdNil sets the value for ProductId to be an explicit nil
func (o *CreateShippingQuoteRequestItemsInner) SetProductIdNil() {
	o.ProductId.Set(nil)
}

// UnsetProductId ensures that no value is present for ProductId, not even an explicit nil
func (o *CreateShippingQuoteRequestItemsInner) UnsetProductId() {
	o.ProductId.Unset()
}

// GetVariantId returns the VariantId field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CreateShippingQuoteRequestItemsInner) GetVariantId() string {
	if o == nil || IsNil(o.VariantId.Get()) {
		var ret string
		return ret
	}
	return *o.VariantId.Get()
}

// GetVariantIdOk returns a tuple with the VariantId field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CreateShippingQuoteRequestItemsInner) GetVariantIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.VariantId.Get(), o.VariantId.IsSet()
}

// HasVariantId returns a boolean if a field has been set.
func (o *CreateShippingQuoteRequestItemsInner) HasVariantId() bool {
	if o != nil && o.VariantId.IsSet() {
		return true
	}

	return false
}

// SetVariantId gets a reference to the given NullableString and assigns it to the VariantId field.
func (o *CreateShippingQuoteRequestItemsInner) SetVariantId(v string) {
	o.VariantId.Set(&v)
}
// SetVariantIdNil sets the value for VariantId to be an explicit nil
func (o *CreateShippingQuoteRequestItemsInner) SetVariantIdNil() {
	o.VariantId.Set(nil)
}

// UnsetVariantId ensures that no value is present for VariantId, not even an explicit nil
func (o *CreateShippingQuoteRequestItemsInner) UnsetVariantId() {
	o.VariantId.Unset()
}

func (o CreateShippingQuoteRequestItemsInner) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateShippingQuoteRequestItemsInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["name"] = o.Name
	if o.Sku.IsSet() {
		toSerialize["sku"] = o.Sku.Get()
	}
	toSerialize["quantity"] = o.Quantity
	toSerialize["grams"] = o.Grams
	toSerialize["price"] = o.Price
	if o.ProductId.IsSet() {
		toSerialize["productId"] = o.ProductId.Get()
	}
	if o.VariantId.IsSet() {
		toSerialize["variantId"] = o.VariantId.Get()
	}
	return toSerialize, nil
}

func (o *CreateShippingQuoteRequestItemsInner) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"name",
		"quantity",
		"grams",
		"price",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCreateShippingQuoteRequestItemsInner := _CreateShippingQuoteRequestItemsInner{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varCreateShippingQuoteRequestItemsInner)

	if err != nil {
		return err
	}

	*o = CreateShippingQuoteRequestItemsInner(varCreateShippingQuoteRequestItemsInner)

	return err
}

type NullableCreateShippingQuoteRequestItemsInner struct {
	value *CreateShippingQuoteRequestItemsInner
	isSet bool
}

func (v NullableCreateShippingQuoteRequestItemsInner) Get() *CreateShippingQuoteRequestItemsInner {
	return v.value
}

func (v *NullableCreateShippingQuoteRequestItemsInner) Set(val *CreateShippingQuoteRequestItemsInner) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateShippingQuoteRequestItemsInner) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateShippingQuoteRequestItemsInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateShippingQuoteRequestItemsInner(val *CreateShippingQuoteRequestItemsInner) *NullableCreateShippingQuoteRequestItemsInner {
	return &NullableCreateShippingQuoteRequestItemsInner{value: val, isSet: true}
}

func (v NullableCreateShippingQuoteRequestItemsInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateShippingQuoteRequestItemsInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


