/*
Zippendo Public API

Public API documentation for Zippendo. Authenticate using your API token (Bearer token prefixed with zipp_).  **Brands (sub-accounts).** An organization can be split into brands, each keeping its own orders, shipments and configuration separate. There are two ways to scope requests to one brand, and NEITHER changes any request body:  1. **Bind the token.** Create an API token with a `brandId` and every request it makes is confined    to that brand — reads filtered, writes stamped. This is the recommended way to give a single    brand's team its own credential. 2. **Send the `X-Zippendo-Brand` header.** An organization-wide token can scope an individual    request by sending the brand's id or slug in this header. Most SDKs let you set it once on the    client so every call inherits it.  A brand-bound token that receives an `X-Zippendo-Brand` header naming a different brand is rejected with `403 BRAND_ACCESS_DENIED` — the binding is never widened. Omit both and requests cover the whole organization, which is the behaviour of every existing token.  Records that belong to no brand carry `brandId: null`. Configuration (carriers, shipping rules, addresses) with a null brand is organization-wide and remains visible inside every brand; orders and shipments with a null brand are only visible organization-wide.  Brands themselves are managed under the **Brands** tag. Retiring a brand is done with `POST /orgs/{orgId}/brands/{brandId}/archive` — permanent deletion is a dashboard-only action, since it is refused while any order, shipment, member or token still references the brand. Brands require a plan that includes them; creating one beyond your plan's limit returns `403`.

API version: 1.0.0
Contact: support@zippendo.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package zippendo

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the VerifyApiToken200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &VerifyApiToken200Response{}

// VerifyApiToken200Response struct for VerifyApiToken200Response
type VerifyApiToken200Response struct {
	// Whether the token is valid
	Valid bool `json:"valid"`
	// Token identifier
	TokenId *string `json:"tokenId,omitempty"`
	// User identifier the token belongs to
	UserId *string `json:"userId,omitempty"`
	// Organization identifier the token belongs to
	OrgId *string `json:"orgId,omitempty"`
	// Permission scopes granted by the token
	Scopes []string `json:"scopes,omitempty"`
	// Expiry timestamp (ISO 8601), null if it never expires
	ExpiresAt NullableString `json:"expiresAt,omitempty"`
}

type _VerifyApiToken200Response VerifyApiToken200Response

// NewVerifyApiToken200Response instantiates a new VerifyApiToken200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewVerifyApiToken200Response(valid bool) *VerifyApiToken200Response {
	this := VerifyApiToken200Response{}
	this.Valid = valid
	return &this
}

// NewVerifyApiToken200ResponseWithDefaults instantiates a new VerifyApiToken200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewVerifyApiToken200ResponseWithDefaults() *VerifyApiToken200Response {
	this := VerifyApiToken200Response{}
	return &this
}

// GetValid returns the Valid field value
func (o *VerifyApiToken200Response) GetValid() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.Valid
}

// GetValidOk returns a tuple with the Valid field value
// and a boolean to check if the value has been set.
func (o *VerifyApiToken200Response) GetValidOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Valid, true
}

// SetValid sets field value
func (o *VerifyApiToken200Response) SetValid(v bool) {
	o.Valid = v
}

// GetTokenId returns the TokenId field value if set, zero value otherwise.
func (o *VerifyApiToken200Response) GetTokenId() string {
	if o == nil || IsNil(o.TokenId) {
		var ret string
		return ret
	}
	return *o.TokenId
}

// GetTokenIdOk returns a tuple with the TokenId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *VerifyApiToken200Response) GetTokenIdOk() (*string, bool) {
	if o == nil || IsNil(o.TokenId) {
		return nil, false
	}
	return o.TokenId, true
}

// HasTokenId returns a boolean if a field has been set.
func (o *VerifyApiToken200Response) HasTokenId() bool {
	if o != nil && !IsNil(o.TokenId) {
		return true
	}

	return false
}

// SetTokenId gets a reference to the given string and assigns it to the TokenId field.
func (o *VerifyApiToken200Response) SetTokenId(v string) {
	o.TokenId = &v
}

// GetUserId returns the UserId field value if set, zero value otherwise.
func (o *VerifyApiToken200Response) GetUserId() string {
	if o == nil || IsNil(o.UserId) {
		var ret string
		return ret
	}
	return *o.UserId
}

// GetUserIdOk returns a tuple with the UserId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *VerifyApiToken200Response) GetUserIdOk() (*string, bool) {
	if o == nil || IsNil(o.UserId) {
		return nil, false
	}
	return o.UserId, true
}

// HasUserId returns a boolean if a field has been set.
func (o *VerifyApiToken200Response) HasUserId() bool {
	if o != nil && !IsNil(o.UserId) {
		return true
	}

	return false
}

// SetUserId gets a reference to the given string and assigns it to the UserId field.
func (o *VerifyApiToken200Response) SetUserId(v string) {
	o.UserId = &v
}

// GetOrgId returns the OrgId field value if set, zero value otherwise.
func (o *VerifyApiToken200Response) GetOrgId() string {
	if o == nil || IsNil(o.OrgId) {
		var ret string
		return ret
	}
	return *o.OrgId
}

// GetOrgIdOk returns a tuple with the OrgId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *VerifyApiToken200Response) GetOrgIdOk() (*string, bool) {
	if o == nil || IsNil(o.OrgId) {
		return nil, false
	}
	return o.OrgId, true
}

// HasOrgId returns a boolean if a field has been set.
func (o *VerifyApiToken200Response) HasOrgId() bool {
	if o != nil && !IsNil(o.OrgId) {
		return true
	}

	return false
}

// SetOrgId gets a reference to the given string and assigns it to the OrgId field.
func (o *VerifyApiToken200Response) SetOrgId(v string) {
	o.OrgId = &v
}

// GetScopes returns the Scopes field value if set, zero value otherwise.
func (o *VerifyApiToken200Response) GetScopes() []string {
	if o == nil || IsNil(o.Scopes) {
		var ret []string
		return ret
	}
	return o.Scopes
}

// GetScopesOk returns a tuple with the Scopes field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *VerifyApiToken200Response) GetScopesOk() ([]string, bool) {
	if o == nil || IsNil(o.Scopes) {
		return nil, false
	}
	return o.Scopes, true
}

// HasScopes returns a boolean if a field has been set.
func (o *VerifyApiToken200Response) HasScopes() bool {
	if o != nil && !IsNil(o.Scopes) {
		return true
	}

	return false
}

// SetScopes gets a reference to the given []string and assigns it to the Scopes field.
func (o *VerifyApiToken200Response) SetScopes(v []string) {
	o.Scopes = v
}

// GetExpiresAt returns the ExpiresAt field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *VerifyApiToken200Response) GetExpiresAt() string {
	if o == nil || IsNil(o.ExpiresAt.Get()) {
		var ret string
		return ret
	}
	return *o.ExpiresAt.Get()
}

// GetExpiresAtOk returns a tuple with the ExpiresAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *VerifyApiToken200Response) GetExpiresAtOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.ExpiresAt.Get(), o.ExpiresAt.IsSet()
}

// HasExpiresAt returns a boolean if a field has been set.
func (o *VerifyApiToken200Response) HasExpiresAt() bool {
	if o != nil && o.ExpiresAt.IsSet() {
		return true
	}

	return false
}

// SetExpiresAt gets a reference to the given NullableString and assigns it to the ExpiresAt field.
func (o *VerifyApiToken200Response) SetExpiresAt(v string) {
	o.ExpiresAt.Set(&v)
}
// SetExpiresAtNil sets the value for ExpiresAt to be an explicit nil
func (o *VerifyApiToken200Response) SetExpiresAtNil() {
	o.ExpiresAt.Set(nil)
}

// UnsetExpiresAt ensures that no value is present for ExpiresAt, not even an explicit nil
func (o *VerifyApiToken200Response) UnsetExpiresAt() {
	o.ExpiresAt.Unset()
}

func (o VerifyApiToken200Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o VerifyApiToken200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["valid"] = o.Valid
	if !IsNil(o.TokenId) {
		toSerialize["tokenId"] = o.TokenId
	}
	if !IsNil(o.UserId) {
		toSerialize["userId"] = o.UserId
	}
	if !IsNil(o.OrgId) {
		toSerialize["orgId"] = o.OrgId
	}
	if !IsNil(o.Scopes) {
		toSerialize["scopes"] = o.Scopes
	}
	if o.ExpiresAt.IsSet() {
		toSerialize["expiresAt"] = o.ExpiresAt.Get()
	}
	return toSerialize, nil
}

func (o *VerifyApiToken200Response) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"valid",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varVerifyApiToken200Response := _VerifyApiToken200Response{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varVerifyApiToken200Response)

	if err != nil {
		return err
	}

	*o = VerifyApiToken200Response(varVerifyApiToken200Response)

	return err
}

type NullableVerifyApiToken200Response struct {
	value *VerifyApiToken200Response
	isSet bool
}

func (v NullableVerifyApiToken200Response) Get() *VerifyApiToken200Response {
	return v.value
}

func (v *NullableVerifyApiToken200Response) Set(val *VerifyApiToken200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableVerifyApiToken200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableVerifyApiToken200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableVerifyApiToken200Response(val *VerifyApiToken200Response) *NullableVerifyApiToken200Response {
	return &NullableVerifyApiToken200Response{value: val, isSet: true}
}

func (v NullableVerifyApiToken200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableVerifyApiToken200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


