/*
Zippendo Public API

Public API documentation for Zippendo. Authenticate using your API token (Bearer token prefixed with zipp_).  **Brands (sub-accounts).** An organization can be split into brands, each keeping its own orders, shipments and configuration separate. There are two ways to scope requests to one brand, and NEITHER changes any request body:  1. **Bind the token.** Create an API token with a `brandId` and every request it makes is confined    to that brand — reads filtered, writes stamped. This is the recommended way to give a single    brand's team its own credential. 2. **Send the `X-Zippendo-Brand` header.** An organization-wide token can scope an individual    request by sending the brand's id or slug in this header. Most SDKs let you set it once on the    client so every call inherits it.  A brand-bound token that receives an `X-Zippendo-Brand` header naming a different brand is rejected with `403 BRAND_ACCESS_DENIED` — the binding is never widened. Omit both and requests cover the whole organization, which is the behaviour of every existing token.  Records that belong to no brand carry `brandId: null`. Configuration (carriers, shipping rules, addresses) with a null brand is organization-wide and remains visible inside every brand; orders and shipments with a null brand are only visible organization-wide.  Brands themselves are managed under the **Brands** tag. Retiring a brand is done with `POST /orgs/{orgId}/brands/{brandId}/archive` — permanent deletion is a dashboard-only action, since it is refused while any order, shipment, member or token still references the brand. Brands require a plan that includes them; creating one beyond your plan's limit returns `403`.

API version: 1.0.0
Contact: support@zippendo.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package zippendo

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the CreateOrderRequestOrderLinesInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateOrderRequestOrderLinesInner{}

// CreateOrderRequestOrderLinesInner struct for CreateOrderRequestOrderLinesInner
type CreateOrderRequestOrderLinesInner struct {
	// Stock keeping unit identifier.
	Sku NullableString `json:"sku,omitempty"`
	// Product name.
	Name string `json:"name"`
	// Quantity ordered.
	Quantity int32 `json:"quantity"`
	// Price per unit.
	UnitPrice NullableFloat32 `json:"unitPrice,omitempty"`
	// Total price for the line.
	TotalPrice NullableFloat32 `json:"totalPrice,omitempty"`
	// ISO 4217 currency code.
	Currency NullableString `json:"currency,omitempty"`
	// Item weight in the given unit.
	Weight NullableFloat32 `json:"weight,omitempty"`
	// Unit of the weight value.
	WeightUnit NullableString `json:"weightUnit,omitempty"`
	// Platform variant identifier.
	VariantId NullableString `json:"variantId,omitempty"`
	// Platform product identifier.
	ProductId NullableString `json:"productId,omitempty"`
	// Product image URL.
	ImageUrl NullableString `json:"imageUrl,omitempty"`
	// Harmonized System customs code (6-13 digits).
	HsCode NullableString `json:"hsCode,omitempty"`
	// ISO 3166-1 alpha-2 country of origin.
	CountryOfOrigin NullableString `json:"countryOfOrigin,omitempty"`
	// ISO 3166-2 province of origin.
	ProvinceOfOrigin NullableString `json:"provinceOfOrigin,omitempty"`
	// Item barcode (EAN/UPC).
	Barcode NullableString `json:"barcode,omitempty"`
	// Whether the item requires shipping.
	RequiresShipping NullableBool `json:"requiresShipping,omitempty"`
	// Whether the item is taxable.
	Taxable NullableBool `json:"taxable,omitempty"`
	// Whether the item is a gift card.
	GiftCard NullableBool `json:"giftCard,omitempty"`
	// Vendor or brand name.
	Vendor NullableString `json:"vendor,omitempty"`
}

type _CreateOrderRequestOrderLinesInner CreateOrderRequestOrderLinesInner

// NewCreateOrderRequestOrderLinesInner instantiates a new CreateOrderRequestOrderLinesInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateOrderRequestOrderLinesInner(name string, quantity int32) *CreateOrderRequestOrderLinesInner {
	this := CreateOrderRequestOrderLinesInner{}
	this.Name = name
	this.Quantity = quantity
	return &this
}

// NewCreateOrderRequestOrderLinesInnerWithDefaults instantiates a new CreateOrderRequestOrderLinesInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateOrderRequestOrderLinesInnerWithDefaults() *CreateOrderRequestOrderLinesInner {
	this := CreateOrderRequestOrderLinesInner{}
	return &this
}

// GetSku returns the Sku field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CreateOrderRequestOrderLinesInner) GetSku() string {
	if o == nil || IsNil(o.Sku.Get()) {
		var ret string
		return ret
	}
	return *o.Sku.Get()
}

// GetSkuOk returns a tuple with the Sku field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CreateOrderRequestOrderLinesInner) GetSkuOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Sku.Get(), o.Sku.IsSet()
}

// HasSku returns a boolean if a field has been set.
func (o *CreateOrderRequestOrderLinesInner) HasSku() bool {
	if o != nil && o.Sku.IsSet() {
		return true
	}

	return false
}

// SetSku gets a reference to the given NullableString and assigns it to the Sku field.
func (o *CreateOrderRequestOrderLinesInner) SetSku(v string) {
	o.Sku.Set(&v)
}
// SetSkuNil sets the value for Sku to be an explicit nil
func (o *CreateOrderRequestOrderLinesInner) SetSkuNil() {
	o.Sku.Set(nil)
}

// UnsetSku ensures that no value is present for Sku, not even an explicit nil
func (o *CreateOrderRequestOrderLinesInner) UnsetSku() {
	o.Sku.Unset()
}

// GetName returns the Name field value
func (o *CreateOrderRequestOrderLinesInner) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *CreateOrderRequestOrderLinesInner) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *CreateOrderRequestOrderLinesInner) SetName(v string) {
	o.Name = v
}

// GetQuantity returns the Quantity field value
func (o *CreateOrderRequestOrderLinesInner) GetQuantity() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Quantity
}

// GetQuantityOk returns a tuple with the Quantity field value
// and a boolean to check if the value has been set.
func (o *CreateOrderRequestOrderLinesInner) GetQuantityOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Quantity, true
}

// SetQuantity sets field value
func (o *CreateOrderRequestOrderLinesInner) SetQuantity(v int32) {
	o.Quantity = v
}

// GetUnitPrice returns the UnitPrice field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CreateOrderRequestOrderLinesInner) GetUnitPrice() float32 {
	if o == nil || IsNil(o.UnitPrice.Get()) {
		var ret float32
		return ret
	}
	return *o.UnitPrice.Get()
}

// GetUnitPriceOk returns a tuple with the UnitPrice field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CreateOrderRequestOrderLinesInner) GetUnitPriceOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return o.UnitPrice.Get(), o.UnitPrice.IsSet()
}

// HasUnitPrice returns a boolean if a field has been set.
func (o *CreateOrderRequestOrderLinesInner) HasUnitPrice() bool {
	if o != nil && o.UnitPrice.IsSet() {
		return true
	}

	return false
}

// SetUnitPrice gets a reference to the given NullableFloat32 and assigns it to the UnitPrice field.
func (o *CreateOrderRequestOrderLinesInner) SetUnitPrice(v float32) {
	o.UnitPrice.Set(&v)
}
// SetUnitPriceNil sets the value for UnitPrice to be an explicit nil
func (o *CreateOrderRequestOrderLinesInner) SetUnitPriceNil() {
	o.UnitPrice.Set(nil)
}

// UnsetUnitPrice ensures that no value is present for UnitPrice, not even an explicit nil
func (o *CreateOrderRequestOrderLinesInner) UnsetUnitPrice() {
	o.UnitPrice.Unset()
}

// GetTotalPrice returns the TotalPrice field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CreateOrderRequestOrderLinesInner) GetTotalPrice() float32 {
	if o == nil || IsNil(o.TotalPrice.Get()) {
		var ret float32
		return ret
	}
	return *o.TotalPrice.Get()
}

// GetTotalPriceOk returns a tuple with the TotalPrice field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CreateOrderRequestOrderLinesInner) GetTotalPriceOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return o.TotalPrice.Get(), o.TotalPrice.IsSet()
}

// HasTotalPrice returns a boolean if a field has been set.
func (o *CreateOrderRequestOrderLinesInner) HasTotalPrice() bool {
	if o != nil && o.TotalPrice.IsSet() {
		return true
	}

	return false
}

// SetTotalPrice gets a reference to the given NullableFloat32 and assigns it to the TotalPrice field.
func (o *CreateOrderRequestOrderLinesInner) SetTotalPrice(v float32) {
	o.TotalPrice.Set(&v)
}
// SetTotalPriceNil sets the value for TotalPrice to be an explicit nil
func (o *CreateOrderRequestOrderLinesInner) SetTotalPriceNil() {
	o.TotalPrice.Set(nil)
}

// UnsetTotalPrice ensures that no value is present for TotalPrice, not even an explicit nil
func (o *CreateOrderRequestOrderLinesInner) UnsetTotalPrice() {
	o.TotalPrice.Unset()
}

// GetCurrency returns the Currency field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CreateOrderRequestOrderLinesInner) GetCurrency() string {
	if o == nil || IsNil(o.Currency.Get()) {
		var ret string
		return ret
	}
	return *o.Currency.Get()
}

// GetCurrencyOk returns a tuple with the Currency field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CreateOrderRequestOrderLinesInner) GetCurrencyOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Currency.Get(), o.Currency.IsSet()
}

// HasCurrency returns a boolean if a field has been set.
func (o *CreateOrderRequestOrderLinesInner) HasCurrency() bool {
	if o != nil && o.Currency.IsSet() {
		return true
	}

	return false
}

// SetCurrency gets a reference to the given NullableString and assigns it to the Currency field.
func (o *CreateOrderRequestOrderLinesInner) SetCurrency(v string) {
	o.Currency.Set(&v)
}
// SetCurrencyNil sets the value for Currency to be an explicit nil
func (o *CreateOrderRequestOrderLinesInner) SetCurrencyNil() {
	o.Currency.Set(nil)
}

// UnsetCurrency ensures that no value is present for Currency, not even an explicit nil
func (o *CreateOrderRequestOrderLinesInner) UnsetCurrency() {
	o.Currency.Unset()
}

// GetWeight returns the Weight field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CreateOrderRequestOrderLinesInner) GetWeight() float32 {
	if o == nil || IsNil(o.Weight.Get()) {
		var ret float32
		return ret
	}
	return *o.Weight.Get()
}

// GetWeightOk returns a tuple with the Weight field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CreateOrderRequestOrderLinesInner) GetWeightOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return o.Weight.Get(), o.Weight.IsSet()
}

// HasWeight returns a boolean if a field has been set.
func (o *CreateOrderRequestOrderLinesInner) HasWeight() bool {
	if o != nil && o.Weight.IsSet() {
		return true
	}

	return false
}

// SetWeight gets a reference to the given NullableFloat32 and assigns it to the Weight field.
func (o *CreateOrderRequestOrderLinesInner) SetWeight(v float32) {
	o.Weight.Set(&v)
}
// SetWeightNil sets the value for Weight to be an explicit nil
func (o *CreateOrderRequestOrderLinesInner) SetWeightNil() {
	o.Weight.Set(nil)
}

// UnsetWeight ensures that no value is present for Weight, not even an explicit nil
func (o *CreateOrderRequestOrderLinesInner) UnsetWeight() {
	o.Weight.Unset()
}

// GetWeightUnit returns the WeightUnit field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CreateOrderRequestOrderLinesInner) GetWeightUnit() string {
	if o == nil || IsNil(o.WeightUnit.Get()) {
		var ret string
		return ret
	}
	return *o.WeightUnit.Get()
}

// GetWeightUnitOk returns a tuple with the WeightUnit field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CreateOrderRequestOrderLinesInner) GetWeightUnitOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.WeightUnit.Get(), o.WeightUnit.IsSet()
}

// HasWeightUnit returns a boolean if a field has been set.
func (o *CreateOrderRequestOrderLinesInner) HasWeightUnit() bool {
	if o != nil && o.WeightUnit.IsSet() {
		return true
	}

	return false
}

// SetWeightUnit gets a reference to the given NullableString and assigns it to the WeightUnit field.
func (o *CreateOrderRequestOrderLinesInner) SetWeightUnit(v string) {
	o.WeightUnit.Set(&v)
}
// SetWeightUnitNil sets the value for WeightUnit to be an explicit nil
func (o *CreateOrderRequestOrderLinesInner) SetWeightUnitNil() {
	o.WeightUnit.Set(nil)
}

// UnsetWeightUnit ensures that no value is present for WeightUnit, not even an explicit nil
func (o *CreateOrderRequestOrderLinesInner) UnsetWeightUnit() {
	o.WeightUnit.Unset()
}

// GetVariantId returns the VariantId field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CreateOrderRequestOrderLinesInner) GetVariantId() string {
	if o == nil || IsNil(o.VariantId.Get()) {
		var ret string
		return ret
	}
	return *o.VariantId.Get()
}

// GetVariantIdOk returns a tuple with the VariantId field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CreateOrderRequestOrderLinesInner) GetVariantIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.VariantId.Get(), o.VariantId.IsSet()
}

// HasVariantId returns a boolean if a field has been set.
func (o *CreateOrderRequestOrderLinesInner) HasVariantId() bool {
	if o != nil && o.VariantId.IsSet() {
		return true
	}

	return false
}

// SetVariantId gets a reference to the given NullableString and assigns it to the VariantId field.
func (o *CreateOrderRequestOrderLinesInner) SetVariantId(v string) {
	o.VariantId.Set(&v)
}
// SetVariantIdNil sets the value for VariantId to be an explicit nil
func (o *CreateOrderRequestOrderLinesInner) SetVariantIdNil() {
	o.VariantId.Set(nil)
}

// UnsetVariantId ensures that no value is present for VariantId, not even an explicit nil
func (o *CreateOrderRequestOrderLinesInner) UnsetVariantId() {
	o.VariantId.Unset()
}

// GetProductId returns the ProductId field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CreateOrderRequestOrderLinesInner) GetProductId() string {
	if o == nil || IsNil(o.ProductId.Get()) {
		var ret string
		return ret
	}
	return *o.ProductId.Get()
}

// GetProductIdOk returns a tuple with the ProductId field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CreateOrderRequestOrderLinesInner) GetProductIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.ProductId.Get(), o.ProductId.IsSet()
}

// HasProductId returns a boolean if a field has been set.
func (o *CreateOrderRequestOrderLinesInner) HasProductId() bool {
	if o != nil && o.ProductId.IsSet() {
		return true
	}

	return false
}

// SetProductId gets a reference to the given NullableString and assigns it to the ProductId field.
func (o *CreateOrderRequestOrderLinesInner) SetProductId(v string) {
	o.ProductId.Set(&v)
}
// SetProductIdNil sets the value for ProductId to be an explicit nil
func (o *CreateOrderRequestOrderLinesInner) SetProductIdNil() {
	o.ProductId.Set(nil)
}

// UnsetProductId ensures that no value is present for ProductId, not even an explicit nil
func (o *CreateOrderRequestOrderLinesInner) UnsetProductId() {
	o.ProductId.Unset()
}

// GetImageUrl returns the ImageUrl field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CreateOrderRequestOrderLinesInner) GetImageUrl() string {
	if o == nil || IsNil(o.ImageUrl.Get()) {
		var ret string
		return ret
	}
	return *o.ImageUrl.Get()
}

// GetImageUrlOk returns a tuple with the ImageUrl field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CreateOrderRequestOrderLinesInner) GetImageUrlOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.ImageUrl.Get(), o.ImageUrl.IsSet()
}

// HasImageUrl returns a boolean if a field has been set.
func (o *CreateOrderRequestOrderLinesInner) HasImageUrl() bool {
	if o != nil && o.ImageUrl.IsSet() {
		return true
	}

	return false
}

// SetImageUrl gets a reference to the given NullableString and assigns it to the ImageUrl field.
func (o *CreateOrderRequestOrderLinesInner) SetImageUrl(v string) {
	o.ImageUrl.Set(&v)
}
// SetImageUrlNil sets the value for ImageUrl to be an explicit nil
func (o *CreateOrderRequestOrderLinesInner) SetImageUrlNil() {
	o.ImageUrl.Set(nil)
}

// UnsetImageUrl ensures that no value is present for ImageUrl, not even an explicit nil
func (o *CreateOrderRequestOrderLinesInner) UnsetImageUrl() {
	o.ImageUrl.Unset()
}

// GetHsCode returns the HsCode field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CreateOrderRequestOrderLinesInner) GetHsCode() string {
	if o == nil || IsNil(o.HsCode.Get()) {
		var ret string
		return ret
	}
	return *o.HsCode.Get()
}

// GetHsCodeOk returns a tuple with the HsCode field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CreateOrderRequestOrderLinesInner) GetHsCodeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.HsCode.Get(), o.HsCode.IsSet()
}

// HasHsCode returns a boolean if a field has been set.
func (o *CreateOrderRequestOrderLinesInner) HasHsCode() bool {
	if o != nil && o.HsCode.IsSet() {
		return true
	}

	return false
}

// SetHsCode gets a reference to the given NullableString and assigns it to the HsCode field.
func (o *CreateOrderRequestOrderLinesInner) SetHsCode(v string) {
	o.HsCode.Set(&v)
}
// SetHsCodeNil sets the value for HsCode to be an explicit nil
func (o *CreateOrderRequestOrderLinesInner) SetHsCodeNil() {
	o.HsCode.Set(nil)
}

// UnsetHsCode ensures that no value is present for HsCode, not even an explicit nil
func (o *CreateOrderRequestOrderLinesInner) UnsetHsCode() {
	o.HsCode.Unset()
}

// GetCountryOfOrigin returns the CountryOfOrigin field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CreateOrderRequestOrderLinesInner) GetCountryOfOrigin() string {
	if o == nil || IsNil(o.CountryOfOrigin.Get()) {
		var ret string
		return ret
	}
	return *o.CountryOfOrigin.Get()
}

// GetCountryOfOriginOk returns a tuple with the CountryOfOrigin field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CreateOrderRequestOrderLinesInner) GetCountryOfOriginOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.CountryOfOrigin.Get(), o.CountryOfOrigin.IsSet()
}

// HasCountryOfOrigin returns a boolean if a field has been set.
func (o *CreateOrderRequestOrderLinesInner) HasCountryOfOrigin() bool {
	if o != nil && o.CountryOfOrigin.IsSet() {
		return true
	}

	return false
}

// SetCountryOfOrigin gets a reference to the given NullableString and assigns it to the CountryOfOrigin field.
func (o *CreateOrderRequestOrderLinesInner) SetCountryOfOrigin(v string) {
	o.CountryOfOrigin.Set(&v)
}
// SetCountryOfOriginNil sets the value for CountryOfOrigin to be an explicit nil
func (o *CreateOrderRequestOrderLinesInner) SetCountryOfOriginNil() {
	o.CountryOfOrigin.Set(nil)
}

// UnsetCountryOfOrigin ensures that no value is present for CountryOfOrigin, not even an explicit nil
func (o *CreateOrderRequestOrderLinesInner) UnsetCountryOfOrigin() {
	o.CountryOfOrigin.Unset()
}

// GetProvinceOfOrigin returns the ProvinceOfOrigin field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CreateOrderRequestOrderLinesInner) GetProvinceOfOrigin() string {
	if o == nil || IsNil(o.ProvinceOfOrigin.Get()) {
		var ret string
		return ret
	}
	return *o.ProvinceOfOrigin.Get()
}

// GetProvinceOfOriginOk returns a tuple with the ProvinceOfOrigin field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CreateOrderRequestOrderLinesInner) GetProvinceOfOriginOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.ProvinceOfOrigin.Get(), o.ProvinceOfOrigin.IsSet()
}

// HasProvinceOfOrigin returns a boolean if a field has been set.
func (o *CreateOrderRequestOrderLinesInner) HasProvinceOfOrigin() bool {
	if o != nil && o.ProvinceOfOrigin.IsSet() {
		return true
	}

	return false
}

// SetProvinceOfOrigin gets a reference to the given NullableString and assigns it to the ProvinceOfOrigin field.
func (o *CreateOrderRequestOrderLinesInner) SetProvinceOfOrigin(v string) {
	o.ProvinceOfOrigin.Set(&v)
}
// SetProvinceOfOriginNil sets the value for ProvinceOfOrigin to be an explicit nil
func (o *CreateOrderRequestOrderLinesInner) SetProvinceOfOriginNil() {
	o.ProvinceOfOrigin.Set(nil)
}

// UnsetProvinceOfOrigin ensures that no value is present for ProvinceOfOrigin, not even an explicit nil
func (o *CreateOrderRequestOrderLinesInner) UnsetProvinceOfOrigin() {
	o.ProvinceOfOrigin.Unset()
}

// GetBarcode returns the Barcode field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CreateOrderRequestOrderLinesInner) GetBarcode() string {
	if o == nil || IsNil(o.Barcode.Get()) {
		var ret string
		return ret
	}
	return *o.Barcode.Get()
}

// GetBarcodeOk returns a tuple with the Barcode field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CreateOrderRequestOrderLinesInner) GetBarcodeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Barcode.Get(), o.Barcode.IsSet()
}

// HasBarcode returns a boolean if a field has been set.
func (o *CreateOrderRequestOrderLinesInner) HasBarcode() bool {
	if o != nil && o.Barcode.IsSet() {
		return true
	}

	return false
}

// SetBarcode gets a reference to the given NullableString and assigns it to the Barcode field.
func (o *CreateOrderRequestOrderLinesInner) SetBarcode(v string) {
	o.Barcode.Set(&v)
}
// SetBarcodeNil sets the value for Barcode to be an explicit nil
func (o *CreateOrderRequestOrderLinesInner) SetBarcodeNil() {
	o.Barcode.Set(nil)
}

// UnsetBarcode ensures that no value is present for Barcode, not even an explicit nil
func (o *CreateOrderRequestOrderLinesInner) UnsetBarcode() {
	o.Barcode.Unset()
}

// GetRequiresShipping returns the RequiresShipping field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CreateOrderRequestOrderLinesInner) GetRequiresShipping() bool {
	if o == nil || IsNil(o.RequiresShipping.Get()) {
		var ret bool
		return ret
	}
	return *o.RequiresShipping.Get()
}

// GetRequiresShippingOk returns a tuple with the RequiresShipping field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CreateOrderRequestOrderLinesInner) GetRequiresShippingOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return o.RequiresShipping.Get(), o.RequiresShipping.IsSet()
}

// HasRequiresShipping returns a boolean if a field has been set.
func (o *CreateOrderRequestOrderLinesInner) HasRequiresShipping() bool {
	if o != nil && o.RequiresShipping.IsSet() {
		return true
	}

	return false
}

// SetRequiresShipping gets a reference to the given NullableBool and assigns it to the RequiresShipping field.
func (o *CreateOrderRequestOrderLinesInner) SetRequiresShipping(v bool) {
	o.RequiresShipping.Set(&v)
}
// SetRequiresShippingNil sets the value for RequiresShipping to be an explicit nil
func (o *CreateOrderRequestOrderLinesInner) SetRequiresShippingNil() {
	o.RequiresShipping.Set(nil)
}

// UnsetRequiresShipping ensures that no value is present for RequiresShipping, not even an explicit nil
func (o *CreateOrderRequestOrderLinesInner) UnsetRequiresShipping() {
	o.RequiresShipping.Unset()
}

// GetTaxable returns the Taxable field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CreateOrderRequestOrderLinesInner) GetTaxable() bool {
	if o == nil || IsNil(o.Taxable.Get()) {
		var ret bool
		return ret
	}
	return *o.Taxable.Get()
}

// GetTaxableOk returns a tuple with the Taxable field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CreateOrderRequestOrderLinesInner) GetTaxableOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return o.Taxable.Get(), o.Taxable.IsSet()
}

// HasTaxable returns a boolean if a field has been set.
func (o *CreateOrderRequestOrderLinesInner) HasTaxable() bool {
	if o != nil && o.Taxable.IsSet() {
		return true
	}

	return false
}

// SetTaxable gets a reference to the given NullableBool and assigns it to the Taxable field.
func (o *CreateOrderRequestOrderLinesInner) SetTaxable(v bool) {
	o.Taxable.Set(&v)
}
// SetTaxableNil sets the value for Taxable to be an explicit nil
func (o *CreateOrderRequestOrderLinesInner) SetTaxableNil() {
	o.Taxable.Set(nil)
}

// UnsetTaxable ensures that no value is present for Taxable, not even an explicit nil
func (o *CreateOrderRequestOrderLinesInner) UnsetTaxable() {
	o.Taxable.Unset()
}

// GetGiftCard returns the GiftCard field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CreateOrderRequestOrderLinesInner) GetGiftCard() bool {
	if o == nil || IsNil(o.GiftCard.Get()) {
		var ret bool
		return ret
	}
	return *o.GiftCard.Get()
}

// GetGiftCardOk returns a tuple with the GiftCard field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CreateOrderRequestOrderLinesInner) GetGiftCardOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return o.GiftCard.Get(), o.GiftCard.IsSet()
}

// HasGiftCard returns a boolean if a field has been set.
func (o *CreateOrderRequestOrderLinesInner) HasGiftCard() bool {
	if o != nil && o.GiftCard.IsSet() {
		return true
	}

	return false
}

// SetGiftCard gets a reference to the given NullableBool and assigns it to the GiftCard field.
func (o *CreateOrderRequestOrderLinesInner) SetGiftCard(v bool) {
	o.GiftCard.Set(&v)
}
// SetGiftCardNil sets the value for GiftCard to be an explicit nil
func (o *CreateOrderRequestOrderLinesInner) SetGiftCardNil() {
	o.GiftCard.Set(nil)
}

// UnsetGiftCard ensures that no value is present for GiftCard, not even an explicit nil
func (o *CreateOrderRequestOrderLinesInner) UnsetGiftCard() {
	o.GiftCard.Unset()
}

// GetVendor returns the Vendor field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CreateOrderRequestOrderLinesInner) GetVendor() string {
	if o == nil || IsNil(o.Vendor.Get()) {
		var ret string
		return ret
	}
	return *o.Vendor.Get()
}

// GetVendorOk returns a tuple with the Vendor field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CreateOrderRequestOrderLinesInner) GetVendorOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Vendor.Get(), o.Vendor.IsSet()
}

// HasVendor returns a boolean if a field has been set.
func (o *CreateOrderRequestOrderLinesInner) HasVendor() bool {
	if o != nil && o.Vendor.IsSet() {
		return true
	}

	return false
}

// SetVendor gets a reference to the given NullableString and assigns it to the Vendor field.
func (o *CreateOrderRequestOrderLinesInner) SetVendor(v string) {
	o.Vendor.Set(&v)
}
// SetVendorNil sets the value for Vendor to be an explicit nil
func (o *CreateOrderRequestOrderLinesInner) SetVendorNil() {
	o.Vendor.Set(nil)
}

// UnsetVendor ensures that no value is present for Vendor, not even an explicit nil
func (o *CreateOrderRequestOrderLinesInner) UnsetVendor() {
	o.Vendor.Unset()
}

func (o CreateOrderRequestOrderLinesInner) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateOrderRequestOrderLinesInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.Sku.IsSet() {
		toSerialize["sku"] = o.Sku.Get()
	}
	toSerialize["name"] = o.Name
	toSerialize["quantity"] = o.Quantity
	if o.UnitPrice.IsSet() {
		toSerialize["unitPrice"] = o.UnitPrice.Get()
	}
	if o.TotalPrice.IsSet() {
		toSerialize["totalPrice"] = o.TotalPrice.Get()
	}
	if o.Currency.IsSet() {
		toSerialize["currency"] = o.Currency.Get()
	}
	if o.Weight.IsSet() {
		toSerialize["weight"] = o.Weight.Get()
	}
	if o.WeightUnit.IsSet() {
		toSerialize["weightUnit"] = o.WeightUnit.Get()
	}
	if o.VariantId.IsSet() {
		toSerialize["variantId"] = o.VariantId.Get()
	}
	if o.ProductId.IsSet() {
		toSerialize["productId"] = o.ProductId.Get()
	}
	if o.ImageUrl.IsSet() {
		toSerialize["imageUrl"] = o.ImageUrl.Get()
	}
	if o.HsCode.IsSet() {
		toSerialize["hsCode"] = o.HsCode.Get()
	}
	if o.CountryOfOrigin.IsSet() {
		toSerialize["countryOfOrigin"] = o.CountryOfOrigin.Get()
	}
	if o.ProvinceOfOrigin.IsSet() {
		toSerialize["provinceOfOrigin"] = o.ProvinceOfOrigin.Get()
	}
	if o.Barcode.IsSet() {
		toSerialize["barcode"] = o.Barcode.Get()
	}
	if o.RequiresShipping.IsSet() {
		toSerialize["requiresShipping"] = o.RequiresShipping.Get()
	}
	if o.Taxable.IsSet() {
		toSerialize["taxable"] = o.Taxable.Get()
	}
	if o.GiftCard.IsSet() {
		toSerialize["giftCard"] = o.GiftCard.Get()
	}
	if o.Vendor.IsSet() {
		toSerialize["vendor"] = o.Vendor.Get()
	}
	return toSerialize, nil
}

func (o *CreateOrderRequestOrderLinesInner) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"name",
		"quantity",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCreateOrderRequestOrderLinesInner := _CreateOrderRequestOrderLinesInner{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varCreateOrderRequestOrderLinesInner)

	if err != nil {
		return err
	}

	*o = CreateOrderRequestOrderLinesInner(varCreateOrderRequestOrderLinesInner)

	return err
}

type NullableCreateOrderRequestOrderLinesInner struct {
	value *CreateOrderRequestOrderLinesInner
	isSet bool
}

func (v NullableCreateOrderRequestOrderLinesInner) Get() *CreateOrderRequestOrderLinesInner {
	return v.value
}

func (v *NullableCreateOrderRequestOrderLinesInner) Set(val *CreateOrderRequestOrderLinesInner) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateOrderRequestOrderLinesInner) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateOrderRequestOrderLinesInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateOrderRequestOrderLinesInner(val *CreateOrderRequestOrderLinesInner) *NullableCreateOrderRequestOrderLinesInner {
	return &NullableCreateOrderRequestOrderLinesInner{value: val, isSet: true}
}

func (v NullableCreateOrderRequestOrderLinesInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateOrderRequestOrderLinesInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


