/*
Zippendo Public API

Public API documentation for Zippendo. Authenticate using your API token (Bearer token prefixed with zipp_).

API version: 1.0.0
Contact: support@zippendo.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package zippendo

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the GetOrg200ResponseCount type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetOrg200ResponseCount{}

// GetOrg200ResponseCount struct for GetOrg200ResponseCount
type GetOrg200ResponseCount struct {
	// Number of members in the organization
	Members float32 `json:"members"`
}

type _GetOrg200ResponseCount GetOrg200ResponseCount

// NewGetOrg200ResponseCount instantiates a new GetOrg200ResponseCount object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetOrg200ResponseCount(members float32) *GetOrg200ResponseCount {
	this := GetOrg200ResponseCount{}
	this.Members = members
	return &this
}

// NewGetOrg200ResponseCountWithDefaults instantiates a new GetOrg200ResponseCount object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetOrg200ResponseCountWithDefaults() *GetOrg200ResponseCount {
	this := GetOrg200ResponseCount{}
	return &this
}

// GetMembers returns the Members field value
func (o *GetOrg200ResponseCount) GetMembers() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.Members
}

// GetMembersOk returns a tuple with the Members field value
// and a boolean to check if the value has been set.
func (o *GetOrg200ResponseCount) GetMembersOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Members, true
}

// SetMembers sets field value
func (o *GetOrg200ResponseCount) SetMembers(v float32) {
	o.Members = v
}

func (o GetOrg200ResponseCount) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetOrg200ResponseCount) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["members"] = o.Members
	return toSerialize, nil
}

func (o *GetOrg200ResponseCount) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"members",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varGetOrg200ResponseCount := _GetOrg200ResponseCount{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varGetOrg200ResponseCount)

	if err != nil {
		return err
	}

	*o = GetOrg200ResponseCount(varGetOrg200ResponseCount)

	return err
}

type NullableGetOrg200ResponseCount struct {
	value *GetOrg200ResponseCount
	isSet bool
}

func (v NullableGetOrg200ResponseCount) Get() *GetOrg200ResponseCount {
	return v.value
}

func (v *NullableGetOrg200ResponseCount) Set(val *GetOrg200ResponseCount) {
	v.value = val
	v.isSet = true
}

func (v NullableGetOrg200ResponseCount) IsSet() bool {
	return v.isSet
}

func (v *NullableGetOrg200ResponseCount) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetOrg200ResponseCount(val *GetOrg200ResponseCount) *NullableGetOrg200ResponseCount {
	return &NullableGetOrg200ResponseCount{value: val, isSet: true}
}

func (v NullableGetOrg200ResponseCount) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetOrg200ResponseCount) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


