/*
Zippendo Public API

Public API documentation for Zippendo. Authenticate using your API token (Bearer token prefixed with zipp_).  **Brands (sub-accounts).** An organization can be split into brands, each keeping its own orders, shipments and configuration separate. There are two ways to scope requests to one brand, and NEITHER changes any request body:  1. **Bind the token.** Create an API token with a `brandId` and every request it makes is confined    to that brand — reads filtered, writes stamped. This is the recommended way to give a single    brand's team its own credential. 2. **Send the `X-Zippendo-Brand` header.** An organization-wide token can scope an individual    request by sending the brand's id or slug in this header. Most SDKs let you set it once on the    client so every call inherits it.  A brand-bound token that receives an `X-Zippendo-Brand` header naming a different brand is rejected with `403 BRAND_ACCESS_DENIED` — the binding is never widened. Omit both and requests cover the whole organization, which is the behaviour of every existing token.  Records that belong to no brand carry `brandId: null`. Configuration (carriers, shipping rules, addresses) with a null brand is organization-wide and remains visible inside every brand; orders and shipments with a null brand are only visible organization-wide.  Brands themselves are managed under the **Brands** tag. Retiring a brand is done with `POST /orgs/{orgId}/brands/{brandId}/archive` — permanent deletion is a dashboard-only action, since it is refused while any order, shipment, member or token still references the brand. Brands require a plan that includes them; creating one beyond your plan's limit returns `403`.

API version: 1.0.0
Contact: support@zippendo.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package zippendo

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the GetBillingUsage200ResponseLimits type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetBillingUsage200ResponseLimits{}

// GetBillingUsage200ResponseLimits struct for GetBillingUsage200ResponseLimits
type GetBillingUsage200ResponseLimits struct {
	TeamMembers GetBillingUsage200ResponseLimitsTeamMembers `json:"teamMembers"`
	Carriers GetBillingUsage200ResponseLimitsTeamMembers `json:"carriers"`
	OrderChannels GetBillingUsage200ResponseLimitsTeamMembers `json:"orderChannels"`
	ShippingRules GetBillingUsage200ResponseLimitsTeamMembers `json:"shippingRules"`
	Addresses GetBillingUsage200ResponseLimitsTeamMembers `json:"addresses"`
	ApiTokens GetBillingUsage200ResponseLimitsTeamMembers `json:"apiTokens"`
	Automations GetBillingUsage200ResponseLimitsTeamMembers `json:"automations"`
}

type _GetBillingUsage200ResponseLimits GetBillingUsage200ResponseLimits

// NewGetBillingUsage200ResponseLimits instantiates a new GetBillingUsage200ResponseLimits object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetBillingUsage200ResponseLimits(teamMembers GetBillingUsage200ResponseLimitsTeamMembers, carriers GetBillingUsage200ResponseLimitsTeamMembers, orderChannels GetBillingUsage200ResponseLimitsTeamMembers, shippingRules GetBillingUsage200ResponseLimitsTeamMembers, addresses GetBillingUsage200ResponseLimitsTeamMembers, apiTokens GetBillingUsage200ResponseLimitsTeamMembers, automations GetBillingUsage200ResponseLimitsTeamMembers) *GetBillingUsage200ResponseLimits {
	this := GetBillingUsage200ResponseLimits{}
	this.TeamMembers = teamMembers
	this.Carriers = carriers
	this.OrderChannels = orderChannels
	this.ShippingRules = shippingRules
	this.Addresses = addresses
	this.ApiTokens = apiTokens
	this.Automations = automations
	return &this
}

// NewGetBillingUsage200ResponseLimitsWithDefaults instantiates a new GetBillingUsage200ResponseLimits object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetBillingUsage200ResponseLimitsWithDefaults() *GetBillingUsage200ResponseLimits {
	this := GetBillingUsage200ResponseLimits{}
	return &this
}

// GetTeamMembers returns the TeamMembers field value
func (o *GetBillingUsage200ResponseLimits) GetTeamMembers() GetBillingUsage200ResponseLimitsTeamMembers {
	if o == nil {
		var ret GetBillingUsage200ResponseLimitsTeamMembers
		return ret
	}

	return o.TeamMembers
}

// GetTeamMembersOk returns a tuple with the TeamMembers field value
// and a boolean to check if the value has been set.
func (o *GetBillingUsage200ResponseLimits) GetTeamMembersOk() (*GetBillingUsage200ResponseLimitsTeamMembers, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TeamMembers, true
}

// SetTeamMembers sets field value
func (o *GetBillingUsage200ResponseLimits) SetTeamMembers(v GetBillingUsage200ResponseLimitsTeamMembers) {
	o.TeamMembers = v
}

// GetCarriers returns the Carriers field value
func (o *GetBillingUsage200ResponseLimits) GetCarriers() GetBillingUsage200ResponseLimitsTeamMembers {
	if o == nil {
		var ret GetBillingUsage200ResponseLimitsTeamMembers
		return ret
	}

	return o.Carriers
}

// GetCarriersOk returns a tuple with the Carriers field value
// and a boolean to check if the value has been set.
func (o *GetBillingUsage200ResponseLimits) GetCarriersOk() (*GetBillingUsage200ResponseLimitsTeamMembers, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Carriers, true
}

// SetCarriers sets field value
func (o *GetBillingUsage200ResponseLimits) SetCarriers(v GetBillingUsage200ResponseLimitsTeamMembers) {
	o.Carriers = v
}

// GetOrderChannels returns the OrderChannels field value
func (o *GetBillingUsage200ResponseLimits) GetOrderChannels() GetBillingUsage200ResponseLimitsTeamMembers {
	if o == nil {
		var ret GetBillingUsage200ResponseLimitsTeamMembers
		return ret
	}

	return o.OrderChannels
}

// GetOrderChannelsOk returns a tuple with the OrderChannels field value
// and a boolean to check if the value has been set.
func (o *GetBillingUsage200ResponseLimits) GetOrderChannelsOk() (*GetBillingUsage200ResponseLimitsTeamMembers, bool) {
	if o == nil {
		return nil, false
	}
	return &o.OrderChannels, true
}

// SetOrderChannels sets field value
func (o *GetBillingUsage200ResponseLimits) SetOrderChannels(v GetBillingUsage200ResponseLimitsTeamMembers) {
	o.OrderChannels = v
}

// GetShippingRules returns the ShippingRules field value
func (o *GetBillingUsage200ResponseLimits) GetShippingRules() GetBillingUsage200ResponseLimitsTeamMembers {
	if o == nil {
		var ret GetBillingUsage200ResponseLimitsTeamMembers
		return ret
	}

	return o.ShippingRules
}

// GetShippingRulesOk returns a tuple with the ShippingRules field value
// and a boolean to check if the value has been set.
func (o *GetBillingUsage200ResponseLimits) GetShippingRulesOk() (*GetBillingUsage200ResponseLimitsTeamMembers, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ShippingRules, true
}

// SetShippingRules sets field value
func (o *GetBillingUsage200ResponseLimits) SetShippingRules(v GetBillingUsage200ResponseLimitsTeamMembers) {
	o.ShippingRules = v
}

// GetAddresses returns the Addresses field value
func (o *GetBillingUsage200ResponseLimits) GetAddresses() GetBillingUsage200ResponseLimitsTeamMembers {
	if o == nil {
		var ret GetBillingUsage200ResponseLimitsTeamMembers
		return ret
	}

	return o.Addresses
}

// GetAddressesOk returns a tuple with the Addresses field value
// and a boolean to check if the value has been set.
func (o *GetBillingUsage200ResponseLimits) GetAddressesOk() (*GetBillingUsage200ResponseLimitsTeamMembers, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Addresses, true
}

// SetAddresses sets field value
func (o *GetBillingUsage200ResponseLimits) SetAddresses(v GetBillingUsage200ResponseLimitsTeamMembers) {
	o.Addresses = v
}

// GetApiTokens returns the ApiTokens field value
func (o *GetBillingUsage200ResponseLimits) GetApiTokens() GetBillingUsage200ResponseLimitsTeamMembers {
	if o == nil {
		var ret GetBillingUsage200ResponseLimitsTeamMembers
		return ret
	}

	return o.ApiTokens
}

// GetApiTokensOk returns a tuple with the ApiTokens field value
// and a boolean to check if the value has been set.
func (o *GetBillingUsage200ResponseLimits) GetApiTokensOk() (*GetBillingUsage200ResponseLimitsTeamMembers, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ApiTokens, true
}

// SetApiTokens sets field value
func (o *GetBillingUsage200ResponseLimits) SetApiTokens(v GetBillingUsage200ResponseLimitsTeamMembers) {
	o.ApiTokens = v
}

// GetAutomations returns the Automations field value
func (o *GetBillingUsage200ResponseLimits) GetAutomations() GetBillingUsage200ResponseLimitsTeamMembers {
	if o == nil {
		var ret GetBillingUsage200ResponseLimitsTeamMembers
		return ret
	}

	return o.Automations
}

// GetAutomationsOk returns a tuple with the Automations field value
// and a boolean to check if the value has been set.
func (o *GetBillingUsage200ResponseLimits) GetAutomationsOk() (*GetBillingUsage200ResponseLimitsTeamMembers, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Automations, true
}

// SetAutomations sets field value
func (o *GetBillingUsage200ResponseLimits) SetAutomations(v GetBillingUsage200ResponseLimitsTeamMembers) {
	o.Automations = v
}

func (o GetBillingUsage200ResponseLimits) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetBillingUsage200ResponseLimits) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["teamMembers"] = o.TeamMembers
	toSerialize["carriers"] = o.Carriers
	toSerialize["orderChannels"] = o.OrderChannels
	toSerialize["shippingRules"] = o.ShippingRules
	toSerialize["addresses"] = o.Addresses
	toSerialize["apiTokens"] = o.ApiTokens
	toSerialize["automations"] = o.Automations
	return toSerialize, nil
}

func (o *GetBillingUsage200ResponseLimits) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"teamMembers",
		"carriers",
		"orderChannels",
		"shippingRules",
		"addresses",
		"apiTokens",
		"automations",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varGetBillingUsage200ResponseLimits := _GetBillingUsage200ResponseLimits{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varGetBillingUsage200ResponseLimits)

	if err != nil {
		return err
	}

	*o = GetBillingUsage200ResponseLimits(varGetBillingUsage200ResponseLimits)

	return err
}

type NullableGetBillingUsage200ResponseLimits struct {
	value *GetBillingUsage200ResponseLimits
	isSet bool
}

func (v NullableGetBillingUsage200ResponseLimits) Get() *GetBillingUsage200ResponseLimits {
	return v.value
}

func (v *NullableGetBillingUsage200ResponseLimits) Set(val *GetBillingUsage200ResponseLimits) {
	v.value = val
	v.isSet = true
}

func (v NullableGetBillingUsage200ResponseLimits) IsSet() bool {
	return v.isSet
}

func (v *NullableGetBillingUsage200ResponseLimits) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetBillingUsage200ResponseLimits(val *GetBillingUsage200ResponseLimits) *NullableGetBillingUsage200ResponseLimits {
	return &NullableGetBillingUsage200ResponseLimits{value: val, isSet: true}
}

func (v NullableGetBillingUsage200ResponseLimits) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetBillingUsage200ResponseLimits) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


