/*
Zippendo Public API

Public API documentation for Zippendo. Authenticate using your API token (Bearer token prefixed with zipp_).  **Brands (sub-accounts).** An organization can be split into brands, each keeping its own orders, shipments and configuration separate. There are two ways to scope requests to one brand, and NEITHER changes any request body:  1. **Bind the token.** Create an API token with a `brandId` and every request it makes is confined    to that brand — reads filtered, writes stamped. This is the recommended way to give a single    brand's team its own credential. 2. **Send the `X-Zippendo-Brand` header.** An organization-wide token can scope an individual    request by sending the brand's id or slug in this header. Most SDKs let you set it once on the    client so every call inherits it.  A brand-bound token that receives an `X-Zippendo-Brand` header naming a different brand is rejected with `403 BRAND_ACCESS_DENIED` — the binding is never widened. Omit both and requests cover the whole organization, which is the behaviour of every existing token.  Records that belong to no brand carry `brandId: null`. Configuration (carriers, shipping rules, addresses) with a null brand is organization-wide and remains visible inside every brand; orders and shipments with a null brand are only visible organization-wide.

API version: 1.0.0
Contact: support@zippendo.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package zippendo

import (
	"encoding/json"
)

// checks if the UpdateCarrierRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UpdateCarrierRequest{}

// UpdateCarrierRequest struct for UpdateCarrierRequest
type UpdateCarrierRequest struct {
	// Carrier display name
	Name *string `json:"name,omitempty"`
	// Carrier slug identifier
	CarrierSlug *string `json:"carrierSlug,omitempty"`
	// Carrier configuration (required and optional fields)
	Config map[string]ListCarriers200ResponseDataInnerConfigValue `json:"config,omitempty"`
}

// NewUpdateCarrierRequest instantiates a new UpdateCarrierRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUpdateCarrierRequest() *UpdateCarrierRequest {
	this := UpdateCarrierRequest{}
	return &this
}

// NewUpdateCarrierRequestWithDefaults instantiates a new UpdateCarrierRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUpdateCarrierRequestWithDefaults() *UpdateCarrierRequest {
	this := UpdateCarrierRequest{}
	return &this
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *UpdateCarrierRequest) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateCarrierRequest) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *UpdateCarrierRequest) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *UpdateCarrierRequest) SetName(v string) {
	o.Name = &v
}

// GetCarrierSlug returns the CarrierSlug field value if set, zero value otherwise.
func (o *UpdateCarrierRequest) GetCarrierSlug() string {
	if o == nil || IsNil(o.CarrierSlug) {
		var ret string
		return ret
	}
	return *o.CarrierSlug
}

// GetCarrierSlugOk returns a tuple with the CarrierSlug field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateCarrierRequest) GetCarrierSlugOk() (*string, bool) {
	if o == nil || IsNil(o.CarrierSlug) {
		return nil, false
	}
	return o.CarrierSlug, true
}

// HasCarrierSlug returns a boolean if a field has been set.
func (o *UpdateCarrierRequest) HasCarrierSlug() bool {
	if o != nil && !IsNil(o.CarrierSlug) {
		return true
	}

	return false
}

// SetCarrierSlug gets a reference to the given string and assigns it to the CarrierSlug field.
func (o *UpdateCarrierRequest) SetCarrierSlug(v string) {
	o.CarrierSlug = &v
}

// GetConfig returns the Config field value if set, zero value otherwise.
func (o *UpdateCarrierRequest) GetConfig() map[string]ListCarriers200ResponseDataInnerConfigValue {
	if o == nil || IsNil(o.Config) {
		var ret map[string]ListCarriers200ResponseDataInnerConfigValue
		return ret
	}
	return o.Config
}

// GetConfigOk returns a tuple with the Config field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateCarrierRequest) GetConfigOk() (map[string]ListCarriers200ResponseDataInnerConfigValue, bool) {
	if o == nil || IsNil(o.Config) {
		return map[string]ListCarriers200ResponseDataInnerConfigValue{}, false
	}
	return o.Config, true
}

// HasConfig returns a boolean if a field has been set.
func (o *UpdateCarrierRequest) HasConfig() bool {
	if o != nil && !IsNil(o.Config) {
		return true
	}

	return false
}

// SetConfig gets a reference to the given map[string]ListCarriers200ResponseDataInnerConfigValue and assigns it to the Config field.
func (o *UpdateCarrierRequest) SetConfig(v map[string]ListCarriers200ResponseDataInnerConfigValue) {
	o.Config = v
}

func (o UpdateCarrierRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UpdateCarrierRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !IsNil(o.CarrierSlug) {
		toSerialize["carrierSlug"] = o.CarrierSlug
	}
	if !IsNil(o.Config) {
		toSerialize["config"] = o.Config
	}
	return toSerialize, nil
}

type NullableUpdateCarrierRequest struct {
	value *UpdateCarrierRequest
	isSet bool
}

func (v NullableUpdateCarrierRequest) Get() *UpdateCarrierRequest {
	return v.value
}

func (v *NullableUpdateCarrierRequest) Set(val *UpdateCarrierRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableUpdateCarrierRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableUpdateCarrierRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUpdateCarrierRequest(val *UpdateCarrierRequest) *NullableUpdateCarrierRequest {
	return &NullableUpdateCarrierRequest{value: val, isSet: true}
}

func (v NullableUpdateCarrierRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUpdateCarrierRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


