/*
Zippendo Public API

Public API documentation for Zippendo. Authenticate using your API token (Bearer token prefixed with zipp_).  **Brands (sub-accounts).** An organization can be split into brands, each keeping its own orders, shipments and configuration separate. There are two ways to scope requests to one brand, and NEITHER changes any request body:  1. **Bind the token.** Create an API token with a `brandId` and every request it makes is confined    to that brand — reads filtered, writes stamped. This is the recommended way to give a single    brand's team its own credential. 2. **Send the `X-Zippendo-Brand` header.** An organization-wide token can scope an individual    request by sending the brand's id or slug in this header. Most SDKs let you set it once on the    client so every call inherits it.  A brand-bound token that receives an `X-Zippendo-Brand` header naming a different brand is rejected with `403 BRAND_ACCESS_DENIED` — the binding is never widened. Omit both and requests cover the whole organization, which is the behaviour of every existing token.  Records that belong to no brand carry `brandId: null`. Configuration (carriers, shipping rules, addresses) with a null brand is organization-wide and remains visible inside every brand; orders and shipments with a null brand are only visible organization-wide.  Brands themselves are managed under the **Brands** tag. Retiring a brand is done with `POST /orgs/{orgId}/brands/{brandId}/archive` — permanent deletion is a dashboard-only action, since it is refused while any order, shipment, member or token still references the brand. Brands require a plan that includes them; creating one beyond your plan's limit returns `403`.

API version: 1.0.0
Contact: support@zippendo.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package zippendo

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the CreateOrgWebhookRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateOrgWebhookRequest{}

// CreateOrgWebhookRequest struct for CreateOrgWebhookRequest
type CreateOrgWebhookRequest struct {
	// Human-readable webhook name
	Name string `json:"name"`
	// Webhook endpoint URL
	Url string `json:"url"`
	// Events to subscribe to
	Events []string `json:"events"`
	// Whether the webhook is active
	IsActive *bool `json:"isActive,omitempty"`
}

type _CreateOrgWebhookRequest CreateOrgWebhookRequest

// NewCreateOrgWebhookRequest instantiates a new CreateOrgWebhookRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateOrgWebhookRequest(name string, url string, events []string) *CreateOrgWebhookRequest {
	this := CreateOrgWebhookRequest{}
	this.Name = name
	this.Url = url
	this.Events = events
	var isActive bool = true
	this.IsActive = &isActive
	return &this
}

// NewCreateOrgWebhookRequestWithDefaults instantiates a new CreateOrgWebhookRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateOrgWebhookRequestWithDefaults() *CreateOrgWebhookRequest {
	this := CreateOrgWebhookRequest{}
	var isActive bool = true
	this.IsActive = &isActive
	return &this
}

// GetName returns the Name field value
func (o *CreateOrgWebhookRequest) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *CreateOrgWebhookRequest) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *CreateOrgWebhookRequest) SetName(v string) {
	o.Name = v
}

// GetUrl returns the Url field value
func (o *CreateOrgWebhookRequest) GetUrl() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Url
}

// GetUrlOk returns a tuple with the Url field value
// and a boolean to check if the value has been set.
func (o *CreateOrgWebhookRequest) GetUrlOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Url, true
}

// SetUrl sets field value
func (o *CreateOrgWebhookRequest) SetUrl(v string) {
	o.Url = v
}

// GetEvents returns the Events field value
func (o *CreateOrgWebhookRequest) GetEvents() []string {
	if o == nil {
		var ret []string
		return ret
	}

	return o.Events
}

// GetEventsOk returns a tuple with the Events field value
// and a boolean to check if the value has been set.
func (o *CreateOrgWebhookRequest) GetEventsOk() ([]string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Events, true
}

// SetEvents sets field value
func (o *CreateOrgWebhookRequest) SetEvents(v []string) {
	o.Events = v
}

// GetIsActive returns the IsActive field value if set, zero value otherwise.
func (o *CreateOrgWebhookRequest) GetIsActive() bool {
	if o == nil || IsNil(o.IsActive) {
		var ret bool
		return ret
	}
	return *o.IsActive
}

// GetIsActiveOk returns a tuple with the IsActive field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateOrgWebhookRequest) GetIsActiveOk() (*bool, bool) {
	if o == nil || IsNil(o.IsActive) {
		return nil, false
	}
	return o.IsActive, true
}

// HasIsActive returns a boolean if a field has been set.
func (o *CreateOrgWebhookRequest) HasIsActive() bool {
	if o != nil && !IsNil(o.IsActive) {
		return true
	}

	return false
}

// SetIsActive gets a reference to the given bool and assigns it to the IsActive field.
func (o *CreateOrgWebhookRequest) SetIsActive(v bool) {
	o.IsActive = &v
}

func (o CreateOrgWebhookRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateOrgWebhookRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["name"] = o.Name
	toSerialize["url"] = o.Url
	toSerialize["events"] = o.Events
	if !IsNil(o.IsActive) {
		toSerialize["isActive"] = o.IsActive
	}
	return toSerialize, nil
}

func (o *CreateOrgWebhookRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"name",
		"url",
		"events",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCreateOrgWebhookRequest := _CreateOrgWebhookRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varCreateOrgWebhookRequest)

	if err != nil {
		return err
	}

	*o = CreateOrgWebhookRequest(varCreateOrgWebhookRequest)

	return err
}

type NullableCreateOrgWebhookRequest struct {
	value *CreateOrgWebhookRequest
	isSet bool
}

func (v NullableCreateOrgWebhookRequest) Get() *CreateOrgWebhookRequest {
	return v.value
}

func (v *NullableCreateOrgWebhookRequest) Set(val *CreateOrgWebhookRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateOrgWebhookRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateOrgWebhookRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateOrgWebhookRequest(val *CreateOrgWebhookRequest) *NullableCreateOrgWebhookRequest {
	return &NullableCreateOrgWebhookRequest{value: val, isSet: true}
}

func (v NullableCreateOrgWebhookRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateOrgWebhookRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


