/*
Zippendo Public API

Public API documentation for Zippendo. Authenticate using your API token (Bearer token prefixed with zipp_).

API version: 1.0.0
Contact: support@zippendo.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package zippendo

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ListShipments200ResponseDataInnerCarrierSettingsAdditionalParametersValueAnyOf type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ListShipments200ResponseDataInnerCarrierSettingsAdditionalParametersValueAnyOf{}

// ListShipments200ResponseDataInnerCarrierSettingsAdditionalParametersValueAnyOf struct for ListShipments200ResponseDataInnerCarrierSettingsAdditionalParametersValueAnyOf
type ListShipments200ResponseDataInnerCarrierSettingsAdditionalParametersValueAnyOf struct {
	// Identifier of the selected service point.
	Id string `json:"id"`
	// Display name of the service point.
	Name string `json:"name"`
	// Formatted address of the service point.
	Address string `json:"address"`
	// Latitude/longitude of the service point.
	Coordinates []CreateShippingRuleRequestAdditionalParametersAnyOfValueAnyOfCoordinatesInner `json:"coordinates,omitempty"`
}

type _ListShipments200ResponseDataInnerCarrierSettingsAdditionalParametersValueAnyOf ListShipments200ResponseDataInnerCarrierSettingsAdditionalParametersValueAnyOf

// NewListShipments200ResponseDataInnerCarrierSettingsAdditionalParametersValueAnyOf instantiates a new ListShipments200ResponseDataInnerCarrierSettingsAdditionalParametersValueAnyOf object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewListShipments200ResponseDataInnerCarrierSettingsAdditionalParametersValueAnyOf(id string, name string, address string) *ListShipments200ResponseDataInnerCarrierSettingsAdditionalParametersValueAnyOf {
	this := ListShipments200ResponseDataInnerCarrierSettingsAdditionalParametersValueAnyOf{}
	this.Id = id
	this.Name = name
	this.Address = address
	return &this
}

// NewListShipments200ResponseDataInnerCarrierSettingsAdditionalParametersValueAnyOfWithDefaults instantiates a new ListShipments200ResponseDataInnerCarrierSettingsAdditionalParametersValueAnyOf object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewListShipments200ResponseDataInnerCarrierSettingsAdditionalParametersValueAnyOfWithDefaults() *ListShipments200ResponseDataInnerCarrierSettingsAdditionalParametersValueAnyOf {
	this := ListShipments200ResponseDataInnerCarrierSettingsAdditionalParametersValueAnyOf{}
	return &this
}

// GetId returns the Id field value
func (o *ListShipments200ResponseDataInnerCarrierSettingsAdditionalParametersValueAnyOf) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *ListShipments200ResponseDataInnerCarrierSettingsAdditionalParametersValueAnyOf) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *ListShipments200ResponseDataInnerCarrierSettingsAdditionalParametersValueAnyOf) SetId(v string) {
	o.Id = v
}

// GetName returns the Name field value
func (o *ListShipments200ResponseDataInnerCarrierSettingsAdditionalParametersValueAnyOf) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *ListShipments200ResponseDataInnerCarrierSettingsAdditionalParametersValueAnyOf) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *ListShipments200ResponseDataInnerCarrierSettingsAdditionalParametersValueAnyOf) SetName(v string) {
	o.Name = v
}

// GetAddress returns the Address field value
func (o *ListShipments200ResponseDataInnerCarrierSettingsAdditionalParametersValueAnyOf) GetAddress() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Address
}

// GetAddressOk returns a tuple with the Address field value
// and a boolean to check if the value has been set.
func (o *ListShipments200ResponseDataInnerCarrierSettingsAdditionalParametersValueAnyOf) GetAddressOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Address, true
}

// SetAddress sets field value
func (o *ListShipments200ResponseDataInnerCarrierSettingsAdditionalParametersValueAnyOf) SetAddress(v string) {
	o.Address = v
}

// GetCoordinates returns the Coordinates field value if set, zero value otherwise.
func (o *ListShipments200ResponseDataInnerCarrierSettingsAdditionalParametersValueAnyOf) GetCoordinates() []CreateShippingRuleRequestAdditionalParametersAnyOfValueAnyOfCoordinatesInner {
	if o == nil || IsNil(o.Coordinates) {
		var ret []CreateShippingRuleRequestAdditionalParametersAnyOfValueAnyOfCoordinatesInner
		return ret
	}
	return o.Coordinates
}

// GetCoordinatesOk returns a tuple with the Coordinates field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ListShipments200ResponseDataInnerCarrierSettingsAdditionalParametersValueAnyOf) GetCoordinatesOk() ([]CreateShippingRuleRequestAdditionalParametersAnyOfValueAnyOfCoordinatesInner, bool) {
	if o == nil || IsNil(o.Coordinates) {
		return nil, false
	}
	return o.Coordinates, true
}

// HasCoordinates returns a boolean if a field has been set.
func (o *ListShipments200ResponseDataInnerCarrierSettingsAdditionalParametersValueAnyOf) HasCoordinates() bool {
	if o != nil && !IsNil(o.Coordinates) {
		return true
	}

	return false
}

// SetCoordinates gets a reference to the given []CreateShippingRuleRequestAdditionalParametersAnyOfValueAnyOfCoordinatesInner and assigns it to the Coordinates field.
func (o *ListShipments200ResponseDataInnerCarrierSettingsAdditionalParametersValueAnyOf) SetCoordinates(v []CreateShippingRuleRequestAdditionalParametersAnyOfValueAnyOfCoordinatesInner) {
	o.Coordinates = v
}

func (o ListShipments200ResponseDataInnerCarrierSettingsAdditionalParametersValueAnyOf) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ListShipments200ResponseDataInnerCarrierSettingsAdditionalParametersValueAnyOf) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["name"] = o.Name
	toSerialize["address"] = o.Address
	if !IsNil(o.Coordinates) {
		toSerialize["coordinates"] = o.Coordinates
	}
	return toSerialize, nil
}

func (o *ListShipments200ResponseDataInnerCarrierSettingsAdditionalParametersValueAnyOf) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"name",
		"address",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varListShipments200ResponseDataInnerCarrierSettingsAdditionalParametersValueAnyOf := _ListShipments200ResponseDataInnerCarrierSettingsAdditionalParametersValueAnyOf{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varListShipments200ResponseDataInnerCarrierSettingsAdditionalParametersValueAnyOf)

	if err != nil {
		return err
	}

	*o = ListShipments200ResponseDataInnerCarrierSettingsAdditionalParametersValueAnyOf(varListShipments200ResponseDataInnerCarrierSettingsAdditionalParametersValueAnyOf)

	return err
}

type NullableListShipments200ResponseDataInnerCarrierSettingsAdditionalParametersValueAnyOf struct {
	value *ListShipments200ResponseDataInnerCarrierSettingsAdditionalParametersValueAnyOf
	isSet bool
}

func (v NullableListShipments200ResponseDataInnerCarrierSettingsAdditionalParametersValueAnyOf) Get() *ListShipments200ResponseDataInnerCarrierSettingsAdditionalParametersValueAnyOf {
	return v.value
}

func (v *NullableListShipments200ResponseDataInnerCarrierSettingsAdditionalParametersValueAnyOf) Set(val *ListShipments200ResponseDataInnerCarrierSettingsAdditionalParametersValueAnyOf) {
	v.value = val
	v.isSet = true
}

func (v NullableListShipments200ResponseDataInnerCarrierSettingsAdditionalParametersValueAnyOf) IsSet() bool {
	return v.isSet
}

func (v *NullableListShipments200ResponseDataInnerCarrierSettingsAdditionalParametersValueAnyOf) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableListShipments200ResponseDataInnerCarrierSettingsAdditionalParametersValueAnyOf(val *ListShipments200ResponseDataInnerCarrierSettingsAdditionalParametersValueAnyOf) *NullableListShipments200ResponseDataInnerCarrierSettingsAdditionalParametersValueAnyOf {
	return &NullableListShipments200ResponseDataInnerCarrierSettingsAdditionalParametersValueAnyOf{value: val, isSet: true}
}

func (v NullableListShipments200ResponseDataInnerCarrierSettingsAdditionalParametersValueAnyOf) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableListShipments200ResponseDataInnerCarrierSettingsAdditionalParametersValueAnyOf) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


