/*
Zippendo Public API

Public API documentation for Zippendo. Authenticate using your API token (Bearer token prefixed with zipp_).

API version: 1.0.0
Contact: support@zippendo.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package zippendo

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ListCarrierProductServicePointsRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ListCarrierProductServicePointsRequest{}

// ListCarrierProductServicePointsRequest struct for ListCarrierProductServicePointsRequest
type ListCarrierProductServicePointsRequest struct {
	// Street address line 1
	Address1 string `json:"address1"`
	// Street address line 2
	Address2 NullableString `json:"address2,omitempty"`
	// Postal code
	PostalCode string `json:"postalCode"`
	// State or region
	State NullableString `json:"state,omitempty"`
	// City name
	City string `json:"city"`
	// ISO 3166-1 alpha-2 country code
	CountryCode string `json:"countryCode"`
}

type _ListCarrierProductServicePointsRequest ListCarrierProductServicePointsRequest

// NewListCarrierProductServicePointsRequest instantiates a new ListCarrierProductServicePointsRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewListCarrierProductServicePointsRequest(address1 string, postalCode string, city string, countryCode string) *ListCarrierProductServicePointsRequest {
	this := ListCarrierProductServicePointsRequest{}
	this.Address1 = address1
	this.PostalCode = postalCode
	this.City = city
	this.CountryCode = countryCode
	return &this
}

// NewListCarrierProductServicePointsRequestWithDefaults instantiates a new ListCarrierProductServicePointsRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewListCarrierProductServicePointsRequestWithDefaults() *ListCarrierProductServicePointsRequest {
	this := ListCarrierProductServicePointsRequest{}
	return &this
}

// GetAddress1 returns the Address1 field value
func (o *ListCarrierProductServicePointsRequest) GetAddress1() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Address1
}

// GetAddress1Ok returns a tuple with the Address1 field value
// and a boolean to check if the value has been set.
func (o *ListCarrierProductServicePointsRequest) GetAddress1Ok() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Address1, true
}

// SetAddress1 sets field value
func (o *ListCarrierProductServicePointsRequest) SetAddress1(v string) {
	o.Address1 = v
}

// GetAddress2 returns the Address2 field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ListCarrierProductServicePointsRequest) GetAddress2() string {
	if o == nil || IsNil(o.Address2.Get()) {
		var ret string
		return ret
	}
	return *o.Address2.Get()
}

// GetAddress2Ok returns a tuple with the Address2 field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ListCarrierProductServicePointsRequest) GetAddress2Ok() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Address2.Get(), o.Address2.IsSet()
}

// HasAddress2 returns a boolean if a field has been set.
func (o *ListCarrierProductServicePointsRequest) HasAddress2() bool {
	if o != nil && o.Address2.IsSet() {
		return true
	}

	return false
}

// SetAddress2 gets a reference to the given NullableString and assigns it to the Address2 field.
func (o *ListCarrierProductServicePointsRequest) SetAddress2(v string) {
	o.Address2.Set(&v)
}
// SetAddress2Nil sets the value for Address2 to be an explicit nil
func (o *ListCarrierProductServicePointsRequest) SetAddress2Nil() {
	o.Address2.Set(nil)
}

// UnsetAddress2 ensures that no value is present for Address2, not even an explicit nil
func (o *ListCarrierProductServicePointsRequest) UnsetAddress2() {
	o.Address2.Unset()
}

// GetPostalCode returns the PostalCode field value
func (o *ListCarrierProductServicePointsRequest) GetPostalCode() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.PostalCode
}

// GetPostalCodeOk returns a tuple with the PostalCode field value
// and a boolean to check if the value has been set.
func (o *ListCarrierProductServicePointsRequest) GetPostalCodeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.PostalCode, true
}

// SetPostalCode sets field value
func (o *ListCarrierProductServicePointsRequest) SetPostalCode(v string) {
	o.PostalCode = v
}

// GetState returns the State field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ListCarrierProductServicePointsRequest) GetState() string {
	if o == nil || IsNil(o.State.Get()) {
		var ret string
		return ret
	}
	return *o.State.Get()
}

// GetStateOk returns a tuple with the State field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ListCarrierProductServicePointsRequest) GetStateOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.State.Get(), o.State.IsSet()
}

// HasState returns a boolean if a field has been set.
func (o *ListCarrierProductServicePointsRequest) HasState() bool {
	if o != nil && o.State.IsSet() {
		return true
	}

	return false
}

// SetState gets a reference to the given NullableString and assigns it to the State field.
func (o *ListCarrierProductServicePointsRequest) SetState(v string) {
	o.State.Set(&v)
}
// SetStateNil sets the value for State to be an explicit nil
func (o *ListCarrierProductServicePointsRequest) SetStateNil() {
	o.State.Set(nil)
}

// UnsetState ensures that no value is present for State, not even an explicit nil
func (o *ListCarrierProductServicePointsRequest) UnsetState() {
	o.State.Unset()
}

// GetCity returns the City field value
func (o *ListCarrierProductServicePointsRequest) GetCity() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.City
}

// GetCityOk returns a tuple with the City field value
// and a boolean to check if the value has been set.
func (o *ListCarrierProductServicePointsRequest) GetCityOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.City, true
}

// SetCity sets field value
func (o *ListCarrierProductServicePointsRequest) SetCity(v string) {
	o.City = v
}

// GetCountryCode returns the CountryCode field value
func (o *ListCarrierProductServicePointsRequest) GetCountryCode() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.CountryCode
}

// GetCountryCodeOk returns a tuple with the CountryCode field value
// and a boolean to check if the value has been set.
func (o *ListCarrierProductServicePointsRequest) GetCountryCodeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CountryCode, true
}

// SetCountryCode sets field value
func (o *ListCarrierProductServicePointsRequest) SetCountryCode(v string) {
	o.CountryCode = v
}

func (o ListCarrierProductServicePointsRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ListCarrierProductServicePointsRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["address1"] = o.Address1
	if o.Address2.IsSet() {
		toSerialize["address2"] = o.Address2.Get()
	}
	toSerialize["postalCode"] = o.PostalCode
	if o.State.IsSet() {
		toSerialize["state"] = o.State.Get()
	}
	toSerialize["city"] = o.City
	toSerialize["countryCode"] = o.CountryCode
	return toSerialize, nil
}

func (o *ListCarrierProductServicePointsRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"address1",
		"postalCode",
		"city",
		"countryCode",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varListCarrierProductServicePointsRequest := _ListCarrierProductServicePointsRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varListCarrierProductServicePointsRequest)

	if err != nil {
		return err
	}

	*o = ListCarrierProductServicePointsRequest(varListCarrierProductServicePointsRequest)

	return err
}

type NullableListCarrierProductServicePointsRequest struct {
	value *ListCarrierProductServicePointsRequest
	isSet bool
}

func (v NullableListCarrierProductServicePointsRequest) Get() *ListCarrierProductServicePointsRequest {
	return v.value
}

func (v *NullableListCarrierProductServicePointsRequest) Set(val *ListCarrierProductServicePointsRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableListCarrierProductServicePointsRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableListCarrierProductServicePointsRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableListCarrierProductServicePointsRequest(val *ListCarrierProductServicePointsRequest) *NullableListCarrierProductServicePointsRequest {
	return &NullableListCarrierProductServicePointsRequest{value: val, isSet: true}
}

func (v NullableListCarrierProductServicePointsRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableListCarrierProductServicePointsRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


