/*
Zippendo Public API

Public API documentation for Zippendo. Authenticate using your API token (Bearer token prefixed with zipp_).  **Brands (sub-accounts).** An organization can be split into brands, each keeping its own orders, shipments and configuration separate. There are two ways to scope requests to one brand, and NEITHER changes any request body:  1. **Bind the token.** Create an API token with a `brandId` and every request it makes is confined    to that brand — reads filtered, writes stamped. This is the recommended way to give a single    brand's team its own credential. 2. **Send the `X-Zippendo-Brand` header.** An organization-wide token can scope an individual    request by sending the brand's id or slug in this header. Most SDKs let you set it once on the    client so every call inherits it.  A brand-bound token that receives an `X-Zippendo-Brand` header naming a different brand is rejected with `403 BRAND_ACCESS_DENIED` — the binding is never widened. Omit both and requests cover the whole organization, which is the behaviour of every existing token.  Records that belong to no brand carry `brandId: null`. Configuration (carriers, shipping rules, addresses) with a null brand is organization-wide and remains visible inside every brand; orders and shipments with a null brand are only visible organization-wide.

API version: 1.0.0
Contact: support@zippendo.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package zippendo

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the CreateShippingQuote404Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateShippingQuote404Response{}

// CreateShippingQuote404Response struct for CreateShippingQuote404Response
type CreateShippingQuote404Response struct {
	// Error type
	Error string `json:"error"`
	// Human-readable error message
	Message string `json:"message"`
}

type _CreateShippingQuote404Response CreateShippingQuote404Response

// NewCreateShippingQuote404Response instantiates a new CreateShippingQuote404Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateShippingQuote404Response(error_ string, message string) *CreateShippingQuote404Response {
	this := CreateShippingQuote404Response{}
	this.Error = error_
	this.Message = message
	return &this
}

// NewCreateShippingQuote404ResponseWithDefaults instantiates a new CreateShippingQuote404Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateShippingQuote404ResponseWithDefaults() *CreateShippingQuote404Response {
	this := CreateShippingQuote404Response{}
	return &this
}

// GetError returns the Error field value
func (o *CreateShippingQuote404Response) GetError() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Error
}

// GetErrorOk returns a tuple with the Error field value
// and a boolean to check if the value has been set.
func (o *CreateShippingQuote404Response) GetErrorOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Error, true
}

// SetError sets field value
func (o *CreateShippingQuote404Response) SetError(v string) {
	o.Error = v
}

// GetMessage returns the Message field value
func (o *CreateShippingQuote404Response) GetMessage() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Message
}

// GetMessageOk returns a tuple with the Message field value
// and a boolean to check if the value has been set.
func (o *CreateShippingQuote404Response) GetMessageOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Message, true
}

// SetMessage sets field value
func (o *CreateShippingQuote404Response) SetMessage(v string) {
	o.Message = v
}

func (o CreateShippingQuote404Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateShippingQuote404Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["error"] = o.Error
	toSerialize["message"] = o.Message
	return toSerialize, nil
}

func (o *CreateShippingQuote404Response) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"error",
		"message",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCreateShippingQuote404Response := _CreateShippingQuote404Response{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varCreateShippingQuote404Response)

	if err != nil {
		return err
	}

	*o = CreateShippingQuote404Response(varCreateShippingQuote404Response)

	return err
}

type NullableCreateShippingQuote404Response struct {
	value *CreateShippingQuote404Response
	isSet bool
}

func (v NullableCreateShippingQuote404Response) Get() *CreateShippingQuote404Response {
	return v.value
}

func (v *NullableCreateShippingQuote404Response) Set(val *CreateShippingQuote404Response) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateShippingQuote404Response) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateShippingQuote404Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateShippingQuote404Response(val *CreateShippingQuote404Response) *NullableCreateShippingQuote404Response {
	return &NullableCreateShippingQuote404Response{value: val, isSet: true}
}

func (v NullableCreateShippingQuote404Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateShippingQuote404Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


